// Package firewall renders the host rule that stops customer VMs sending mail.
//
// Outbound SMTP (TCP 25) from the VM bridge is dropped for everyone, which
// keeps new accounts from being used for spam and protects the host's IP
// reputation. A VM with port25_unblocked set (after manual review) is exempt.
// The rules run in the forward hook because routed VM traffic crosses the host.
package firewall

import (
	"fmt"
	"net/netip"
	"sort"
	"strings"
)

// Render returns an nftables ruleset for the given bridge and exempt addresses.
// Invalid addresses are rejected rather than written into a firewall rule.
func Render(bridge string, allowV4, allowV6 []string) (string, error) {
	if bridge == "" || strings.ContainsAny(bridge, " \t\n\"{};") {
		return "", fmt.Errorf("firewall: invalid bridge name %q", bridge)
	}
	v4, err := clean(allowV4, true)
	if err != nil {
		return "", err
	}
	v6, err := clean(allowV6, false)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Generated by `xenosctl firewall nft`. Do not edit; regenerate after changing port-25 exemptions.\n")
	b.WriteString("table inet xenos_mail\ndelete table inet xenos_mail\n\ntable inet xenos_mail {\n")
	writeSet(&b, "allow_smtp4", "ipv4_addr", v4)
	writeSet(&b, "allow_smtp6", "ipv6_addr", v6)
	fmt.Fprintf(&b, "\tchain forward {\n\t\ttype filter hook forward priority 0; policy accept;\n")
	fmt.Fprintf(&b, "\t\tiifname %q ip saddr @allow_smtp4 tcp dport 25 accept\n", bridge)
	fmt.Fprintf(&b, "\t\tiifname %q ip6 saddr @allow_smtp6 tcp dport 25 accept\n", bridge)
	fmt.Fprintf(&b, "\t\tiifname %q tcp dport 25 counter drop comment \"outbound SMTP blocked\"\n", bridge)
	b.WriteString("\t}\n}\n")
	return b.String(), nil
}

func writeSet(b *strings.Builder, name, typ string, addrs []string) {
	fmt.Fprintf(b, "\tset %s {\n\t\ttype %s\n", name, typ)
	if len(addrs) > 0 {
		fmt.Fprintf(b, "\t\telements = { %s }\n", strings.Join(addrs, ", "))
	}
	b.WriteString("\t}\n")
}

func clean(in []string, want4 bool) ([]string, error) {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if s == "" {
			continue
		}
		a, err := netip.ParseAddr(strings.TrimSpace(s))
		if err != nil || a.Is4() != want4 {
			return nil, fmt.Errorf("firewall: bad address %q", s)
		}
		if !seen[a.String()] {
			seen[a.String()] = true
			out = append(out, a.String())
		}
	}
	sort.Strings(out)
	return out, nil
}
