// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminListUsers = `-- name: AdminListUsers :many
SELECT u.id, u.email, u.status, u.is_admin, u.vm_limit, u.email_verified_at, u.created_at, u.ispend_customer_id,
       (SELECT count(*) FROM vms v WHERE v.user_id = u.id AND v.state NOT IN ('deleted', 'error'))::int AS vm_count
FROM users u
WHERE ($1::text = '' OR u.email ILIKE '%' || $1 || '%')
ORDER BY u.id DESC
LIMIT $2 OFFSET $3
`

type AdminListUsersParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type AdminListUsersRow struct {
	ID               int64              `json:"id"`
	Email            string             `json:"email"`
	Status           string             `json:"status"`
	IsAdmin          bool               `json:"is_admin"`
	VmLimit          int32              `json:"vm_limit"`
	EmailVerifiedAt  pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt        time.Time          `json:"created_at"`
	IspendCustomerID pgtype.Text        `json:"ispend_customer_id"`
	VmCount          int32              `json:"vm_count"`
}

func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Status,
			&i.IsAdmin,
			&i.VmLimit,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.IspendCustomerID,
			&i.VmCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListVMs = `-- name: AdminListVMs :many
SELECT v.id, v.hostname, v.state, v.region, v.created_at, v.flagged_at, COALESCE(v.flag_reason, '')::text AS flag_reason,
       v.port25_unblocked, v.user_id, u.email, p.slug AS plan_slug, p.price_uusdt_hourly,
       COALESCE(host(ip.address), '')::text AS ipv4, COALESCE(v.ipv6, '')::text AS ipv6
FROM vms v
JOIN users u ON u.id = v.user_id
JOIN plans p ON p.id = v.plan_id
LEFT JOIN ip_addresses ip ON ip.id = v.ipv4_id
WHERE v.deleted_at IS NULL
  AND ($1::text = '' OR v.state = $1)
  AND ($2::text = '' OR u.email ILIKE '%' || $2 || '%' OR v.hostname ILIKE '%' || $2 || '%')
  AND (NOT $3::bool OR v.flagged_at IS NOT NULL)
ORDER BY v.id DESC
LIMIT 200
`

type AdminListVMsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 bool   `json:"column_3"`
}

type AdminListVMsRow struct {
	ID               int64              `json:"id"`
	Hostname         string             `json:"hostname"`
	State            string             `json:"state"`
	Region           string             `json:"region"`
	CreatedAt        time.Time          `json:"created_at"`
	FlaggedAt        pgtype.Timestamptz `json:"flagged_at"`
	FlagReason       string             `json:"flag_reason"`
	Port25Unblocked  bool               `json:"port25_unblocked"`
	UserID           int64              `json:"user_id"`
	Email            string             `json:"email"`
	PlanSlug         string             `json:"plan_slug"`
	PriceUusdtHourly int64              `json:"price_uusdt_hourly"`
	Ipv4             string             `json:"ipv4"`
	Ipv6             string             `json:"ipv6"`
}

func (q *Queries) AdminListVMs(ctx context.Context, arg AdminListVMsParams) ([]AdminListVMsRow, error) {
	rows, err := q.db.Query(ctx, adminListVMs, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListVMsRow{}
	for rows.Next() {
		var i AdminListVMsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.State,
			&i.Region,
			&i.CreatedAt,
			&i.FlaggedAt,
			&i.FlagReason,
			&i.Port25Unblocked,
			&i.UserID,
			&i.Email,
			&i.PlanSlug,
			&i.PriceUusdtHourly,
			&i.Ipv4,
			&i.Ipv6,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const committedVCPU = `-- name: CommittedVCPU :one
SELECT COALESCE(sum(p.vcpu), 0)::bigint FROM vms v JOIN plans p ON p.id = v.plan_id
WHERE v.state IN ('pending', 'provisioning', 'running')
`

func (q *Queries) CommittedVCPU(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, committedVCPU)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const completeAdjustment = `-- name: CompleteAdjustment :exec
UPDATE adjustments SET status = 'complete', ispend_movement_id = $2, last_error = NULL WHERE id = $1
`

type CompleteAdjustmentParams struct {
	ID               int64       `json:"id"`
	IspendMovementID pgtype.Text `json:"ispend_movement_id"`
}

func (q *Queries) CompleteAdjustment(ctx context.Context, arg CompleteAdjustmentParams) error {
	_, err := q.db.Exec(ctx, completeAdjustment, arg.ID, arg.IspendMovementID)
	return err
}

const countTotalIPs = `-- name: CountTotalIPs :one
SELECT count(*) FROM ip_addresses
`

func (q *Queries) CountTotalIPs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalIPs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdjustment = `-- name: CreateAdjustment :one
INSERT INTO adjustments (admin_id, user_id, amount_uusdt, note, request_id) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (admin_id, request_id) WHERE request_id IS NOT NULL DO NOTHING
RETURNING id
`

type CreateAdjustmentParams struct {
	AdminID     int64       `json:"admin_id"`
	UserID      int64       `json:"user_id"`
	AmountUusdt int64       `json:"amount_uusdt"`
	Note        string      `json:"note"`
	RequestID   pgtype.Text `json:"request_id"`
}

// A repeat of (admin, request_id) inserts nothing and returns no row: the caller then reads the original.
func (q *Queries) CreateAdjustment(ctx context.Context, arg CreateAdjustmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAdjustment,
		arg.AdminID,
		arg.UserID,
		arg.AmountUusdt,
		arg.Note,
		arg.RequestID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const failAdjustment = `-- name: FailAdjustment :exec
UPDATE adjustments SET status = 'failed', last_error = $2 WHERE id = $1
`

type FailAdjustmentParams struct {
	ID        int64       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) FailAdjustment(ctx context.Context, arg FailAdjustmentParams) error {
	_, err := q.db.Exec(ctx, failAdjustment, arg.ID, arg.LastError)
	return err
}

const getAdjustmentByRequest = `-- name: GetAdjustmentByRequest :one
SELECT id, user_id, amount_uusdt, note, status FROM adjustments WHERE admin_id = $1 AND request_id = $2
`

type GetAdjustmentByRequestParams struct {
	AdminID   int64       `json:"admin_id"`
	RequestID pgtype.Text `json:"request_id"`
}

type GetAdjustmentByRequestRow struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
	AmountUusdt int64  `json:"amount_uusdt"`
	Note        string `json:"note"`
	Status      string `json:"status"`
}

func (q *Queries) GetAdjustmentByRequest(ctx context.Context, arg GetAdjustmentByRequestParams) (GetAdjustmentByRequestRow, error) {
	row := q.db.QueryRow(ctx, getAdjustmentByRequest, arg.AdminID, arg.RequestID)
	var i GetAdjustmentByRequestRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountUusdt,
		&i.Note,
		&i.Status,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO admin_audit (admin_id, action, target, detail) VALUES ($1, $2, $3, $4)
`

type InsertAuditParams struct {
	AdminID int64  `json:"admin_id"`
	Action  string `json:"action"`
	Target  string `json:"target"`
	Detail  []byte `json:"detail"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.AdminID,
		arg.Action,
		arg.Target,
		arg.Detail,
	)
	return err
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT id, kind, payload, status, attempts, COALESCE(last_error, '')::text AS last_error, created_at
FROM jobs WHERE status = $1 ORDER BY id DESC LIMIT 100
`

type ListJobsByStatusRow struct {
	ID        int64     `json:"id"`
	Kind      string    `json:"kind"`
	Payload   []byte    `json:"payload"`
	Status    string    `json:"status"`
	Attempts  int32     `json:"attempts"`
	LastError string    `json:"last_error"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListJobsByStatus(ctx context.Context, status string) ([]ListJobsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listJobsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsByStatusRow{}
	for rows.Next() {
		var i ListJobsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAdjustments = `-- name: ListUserAdjustments :many
SELECT a.id, a.amount_uusdt, a.note, a.status, a.created_at, adm.email AS admin_email
FROM adjustments a JOIN users adm ON adm.id = a.admin_id
WHERE a.user_id = $1 ORDER BY a.id DESC LIMIT 20
`

type ListUserAdjustmentsRow struct {
	ID          int64     `json:"id"`
	AmountUusdt int64     `json:"amount_uusdt"`
	Note        string    `json:"note"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	AdminEmail  string    `json:"admin_email"`
}

func (q *Queries) ListUserAdjustments(ctx context.Context, userID int64) ([]ListUserAdjustmentsRow, error) {
	rows, err := q.db.Query(ctx, listUserAdjustments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAdjustmentsRow{}
	for rows.Next() {
		var i ListUserAdjustmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountUusdt,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
			&i.AdminEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJob = `-- name: RetryJob :execrows
UPDATE jobs SET status = 'queued', attempts = 0, run_after = now(), alerted_at = NULL WHERE id = $1 AND status = 'failed'
`

func (q *Queries) RetryJob(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, retryJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revenueByDay = `-- name: RevenueByDay :many
SELECT d::date AS day,
       COALESCE((SELECT sum(c.amount_ngn_kobo) FROM conversions c
                 WHERE c.status = 'complete' AND c.created_at >= d AND c.created_at < d + interval '1 day'), 0)::bigint AS converted_ngn_kobo,
       COALESCE((SELECT sum(c.amount_uusdt) FROM conversions c
                 WHERE c.status = 'complete' AND c.created_at >= d AND c.created_at < d + interval '1 day'), 0)::bigint AS converted_uusdt,
       COALESCE((SELECT sum(x.amount_uusdt) FROM usage_charges x
                 WHERE x.status = 'paid' AND x.hour >= d AND x.hour < d + interval '1 day'), 0)::bigint AS usage_uusdt
FROM generate_series($1::timestamptz, $2::timestamptz, interval '1 day') AS d
ORDER BY d DESC
`

type RevenueByDayParams struct {
	Column1 time.Time `json:"column_1"`
	Column2 time.Time `json:"column_2"`
}

type RevenueByDayRow struct {
	Day              pgtype.Date `json:"day"`
	ConvertedNgnKobo int64       `json:"converted_ngn_kobo"`
	ConvertedUusdt   int64       `json:"converted_uusdt"`
	UsageUusdt       int64       `json:"usage_uusdt"`
}

func (q *Queries) RevenueByDay(ctx context.Context, arg RevenueByDayParams) ([]RevenueByDayRow, error) {
	rows, err := q.db.Query(ctx, revenueByDay, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueByDayRow{}
	for rows.Next() {
		var i RevenueByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.ConvertedNgnKobo,
			&i.ConvertedUusdt,
			&i.UsageUusdt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserStatusByID = `-- name: SetUserStatusByID :execrows
UPDATE users SET status = $2 WHERE id = $1
`

type SetUserStatusByIDParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetUserStatusByID(ctx context.Context, arg SetUserStatusByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserStatusByID, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserVMLimit = `-- name: SetUserVMLimit :execrows
UPDATE users SET vm_limit = $2 WHERE id = $1
`

type SetUserVMLimitParams struct {
	ID      int64 `json:"id"`
	VmLimit int32 `json:"vm_limit"`
}

func (q *Queries) SetUserVMLimit(ctx context.Context, arg SetUserVMLimitParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserVMLimit, arg.ID, arg.VmLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumAdminAdjustments24h = `-- name: SumAdminAdjustments24h :one
SELECT COALESCE(sum(abs(amount_uusdt)), 0)::bigint FROM adjustments
WHERE admin_id = $1 AND status <> 'failed' AND created_at > now() - interval '24 hours'
`

func (q *Queries) SumAdminAdjustments24h(ctx context.Context, adminID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumAdminAdjustments24h, adminID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
