// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAPITokens = `-- name: CountAPITokens :one
SELECT count(*) FROM api_tokens WHERE user_id = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) CountAPITokens(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAPITokens, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, prefix, token_hash, expires_at) VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateAPITokenParams struct {
	UserID    int64              `json:"user_id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAPITokenUser = `-- name: GetAPITokenUser :one
SELECT t.id AS token_id, t.token_hash, u.id, u.email, u.password_hash, u.ispend_customer_id, u.email_verified_at, u.phone, u.status, u.is_admin, u.vm_limit, u.auto_convert, u.created_at, u.grace_started_at, u.low_balance_notified_at, u.aup_accepted_at, u.va_bank, u.va_account_number, u.va_account_name, u.closing_at, u.purge_after, u.closed_at
FROM api_tokens t JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1 AND t.revoked_at IS NULL AND (t.expires_at IS NULL OR t.expires_at > now())
`

type GetAPITokenUserRow struct {
	TokenID              int64              `json:"token_id"`
	TokenHash            []byte             `json:"token_hash"`
	ID                   int64              `json:"id"`
	Email                string             `json:"email"`
	PasswordHash         string             `json:"password_hash"`
	IspendCustomerID     pgtype.Text        `json:"ispend_customer_id"`
	EmailVerifiedAt      pgtype.Timestamptz `json:"email_verified_at"`
	Phone                string             `json:"phone"`
	Status               string             `json:"status"`
	IsAdmin              bool               `json:"is_admin"`
	VmLimit              int32              `json:"vm_limit"`
	AutoConvert          bool               `json:"auto_convert"`
	CreatedAt            time.Time          `json:"created_at"`
	GraceStartedAt       pgtype.Timestamptz `json:"grace_started_at"`
	LowBalanceNotifiedAt pgtype.Timestamptz `json:"low_balance_notified_at"`
	AupAcceptedAt        pgtype.Timestamptz `json:"aup_accepted_at"`
	VaBank               pgtype.Text        `json:"va_bank"`
	VaAccountNumber      pgtype.Text        `json:"va_account_number"`
	VaAccountName        pgtype.Text        `json:"va_account_name"`
	ClosingAt            pgtype.Timestamptz `json:"closing_at"`
	PurgeAfter           pgtype.Timestamptz `json:"purge_after"`
	ClosedAt             pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) GetAPITokenUser(ctx context.Context, tokenHash []byte) (GetAPITokenUserRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenUser, tokenHash)
	var i GetAPITokenUserRow
	err := row.Scan(
		&i.TokenID,
		&i.TokenHash,
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IspendCustomerID,
		&i.EmailVerifiedAt,
		&i.Phone,
		&i.Status,
		&i.IsAdmin,
		&i.VmLimit,
		&i.AutoConvert,
		&i.CreatedAt,
		&i.GraceStartedAt,
		&i.LowBalanceNotifiedAt,
		&i.AupAcceptedAt,
		&i.VaBank,
		&i.VaAccountNumber,
		&i.VaAccountName,
		&i.ClosingAt,
		&i.PurgeAfter,
		&i.ClosedAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, name, prefix, created_at, last_used_at, expires_at
FROM api_tokens WHERE user_id = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now()) ORDER BY id DESC
`

type ListAPITokensRow struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	CreatedAt  time.Time          `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListAPITokens(ctx context.Context, userID int64) ([]ListAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensRow{}
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens SET revoked_at = now() WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserAPITokens = `-- name: RevokeUserAPITokens :exec
UPDATE api_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserAPITokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeUserAPITokens, userID)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

func (q *Queries) TouchAPIToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}
