// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeConversion = `-- name: CompleteConversion :exec
UPDATE conversions
SET status = 'complete', amount_uusdt = $2, rate = NULLIF($3::text, '')::numeric, ispend_quote_id = $4, ispend_movement_id = $5, last_error = NULL
WHERE id = $1
`

type CompleteConversionParams struct {
	ID               int64       `json:"id"`
	AmountUusdt      pgtype.Int8 `json:"amount_uusdt"`
	Column3          string      `json:"column_3"`
	IspendQuoteID    pgtype.Text `json:"ispend_quote_id"`
	IspendMovementID pgtype.Text `json:"ispend_movement_id"`
}

func (q *Queries) CompleteConversion(ctx context.Context, arg CompleteConversionParams) error {
	_, err := q.db.Exec(ctx, completeConversion,
		arg.ID,
		arg.AmountUusdt,
		arg.Column3,
		arg.IspendQuoteID,
		arg.IspendMovementID,
	)
	return err
}

const createConversion = `-- name: CreateConversion :one
INSERT INTO conversions (user_id, amount_ngn_kobo, deposit_event_id, ispend_quote_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (deposit_event_id) DO NOTHING
RETURNING id
`

type CreateConversionParams struct {
	UserID         int64       `json:"user_id"`
	AmountNgnKobo  int64       `json:"amount_ngn_kobo"`
	DepositEventID pgtype.Text `json:"deposit_event_id"`
	IspendQuoteID  pgtype.Text `json:"ispend_quote_id"`
}

func (q *Queries) CreateConversion(ctx context.Context, arg CreateConversionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createConversion,
		arg.UserID,
		arg.AmountNgnKobo,
		arg.DepositEventID,
		arg.IspendQuoteID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const failConversion = `-- name: FailConversion :exec
UPDATE conversions SET status = 'failed', last_error = $2 WHERE id = $1
`

type FailConversionParams struct {
	ID        int64       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) FailConversion(ctx context.Context, arg FailConversionParams) error {
	_, err := q.db.Exec(ctx, failConversion, arg.ID, arg.LastError)
	return err
}

const getConversion = `-- name: GetConversion :one
SELECT id, user_id, ispend_quote_id, amount_ngn_kobo, amount_uusdt, rate, ispend_movement_id, deposit_event_id, status, created_at, last_error, convert_attempt FROM conversions WHERE id = $1
`

func (q *Queries) GetConversion(ctx context.Context, id int64) (Conversion, error) {
	row := q.db.QueryRow(ctx, getConversion, id)
	var i Conversion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IspendQuoteID,
		&i.AmountNgnKobo,
		&i.AmountUusdt,
		&i.Rate,
		&i.IspendMovementID,
		&i.DepositEventID,
		&i.Status,
		&i.CreatedAt,
		&i.LastError,
		&i.ConvertAttempt,
	)
	return i, err
}

const getConversionByKey = `-- name: GetConversionByKey :one
SELECT id, user_id, ispend_quote_id, amount_ngn_kobo, amount_uusdt, rate, ispend_movement_id, deposit_event_id, status, created_at, last_error, convert_attempt FROM conversions WHERE deposit_event_id = $1
`

func (q *Queries) GetConversionByKey(ctx context.Context, depositEventID pgtype.Text) (Conversion, error) {
	row := q.db.QueryRow(ctx, getConversionByKey, depositEventID)
	var i Conversion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IspendQuoteID,
		&i.AmountNgnKobo,
		&i.AmountUusdt,
		&i.Rate,
		&i.IspendMovementID,
		&i.DepositEventID,
		&i.Status,
		&i.CreatedAt,
		&i.LastError,
		&i.ConvertAttempt,
	)
	return i, err
}

const getUserByISpendCustomer = `-- name: GetUserByISpendCustomer :one
SELECT id, email, password_hash, ispend_customer_id, email_verified_at, phone, status, is_admin, vm_limit, auto_convert, created_at, grace_started_at, low_balance_notified_at, aup_accepted_at, va_bank, va_account_number, va_account_name, closing_at, purge_after, closed_at FROM users WHERE ispend_customer_id = $1
`

func (q *Queries) GetUserByISpendCustomer(ctx context.Context, ispendCustomerID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByISpendCustomer, ispendCustomerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IspendCustomerID,
		&i.EmailVerifiedAt,
		&i.Phone,
		&i.Status,
		&i.IsAdmin,
		&i.VmLimit,
		&i.AutoConvert,
		&i.CreatedAt,
		&i.GraceStartedAt,
		&i.LowBalanceNotifiedAt,
		&i.AupAcceptedAt,
		&i.VaBank,
		&i.VaAccountNumber,
		&i.VaAccountName,
		&i.ClosingAt,
		&i.PurgeAfter,
		&i.ClosedAt,
	)
	return i, err
}

const getUserQuote = `-- name: GetUserQuote :one
SELECT id, user_id, amount_ngn_kobo, amount_uusdt, rate, created_at, expires_at FROM conversion_quotes WHERE id = $1 AND user_id = $2
`

type GetUserQuoteParams struct {
	ID     string `json:"id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) GetUserQuote(ctx context.Context, arg GetUserQuoteParams) (ConversionQuote, error) {
	row := q.db.QueryRow(ctx, getUserQuote, arg.ID, arg.UserID)
	var i ConversionQuote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountNgnKobo,
		&i.AmountUusdt,
		&i.Rate,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertDepositReversal = `-- name: InsertDepositReversal :execrows
INSERT INTO deposit_reversals (event_key, user_id, wallet_id, amount_kobo, uncovered_kobo, original_ref)
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (event_key) DO NOTHING
`

type InsertDepositReversalParams struct {
	EventKey      string      `json:"event_key"`
	UserID        pgtype.Int8 `json:"user_id"`
	WalletID      string      `json:"wallet_id"`
	AmountKobo    int64       `json:"amount_kobo"`
	UncoveredKobo int64       `json:"uncovered_kobo"`
	OriginalRef   string      `json:"original_ref"`
}

func (q *Queries) InsertDepositReversal(ctx context.Context, arg InsertDepositReversalParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDepositReversal,
		arg.EventKey,
		arg.UserID,
		arg.WalletID,
		arg.AmountKobo,
		arg.UncoveredKobo,
		arg.OriginalRef,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :execrows
INSERT INTO webhook_events (id) VALUES ($1) ON CONFLICT (id) DO NOTHING
`

func (q *Queries) InsertWebhookEvent(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listStalledConversions = `-- name: ListStalledConversions :many
SELECT c.id FROM conversions c
WHERE c.status = 'pending'
  AND NOT EXISTS (SELECT 1 FROM jobs j WHERE j.kind = 'conversion.run' AND j.status IN ('queued', 'running')
                  AND j.payload->>'conversion_id' = c.id::text)
`

func (q *Queries) ListStalledConversions(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listStalledConversions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCharges = `-- name: ListUserCharges :many
SELECT c.id, COALESCE(c.vm_id, 0)::bigint AS vm_id, COALESCE(v.hostname, 'floating ' || host(f.address))::text AS hostname, c.hour, c.amount_uusdt, c.status
FROM usage_charges c LEFT JOIN vms v ON v.id = c.vm_id LEFT JOIN floating_ips f ON f.id = c.floating_ip_id
WHERE c.user_id = $1 ORDER BY c.hour DESC, c.id DESC LIMIT 24
`

type ListUserChargesRow struct {
	ID          int64     `json:"id"`
	VmID        int64     `json:"vm_id"`
	Hostname    string    `json:"hostname"`
	Hour        time.Time `json:"hour"`
	AmountUusdt int64     `json:"amount_uusdt"`
	Status      string    `json:"status"`
}

func (q *Queries) ListUserCharges(ctx context.Context, userID int64) ([]ListUserChargesRow, error) {
	rows, err := q.db.Query(ctx, listUserCharges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserChargesRow{}
	for rows.Next() {
		var i ListUserChargesRow
		if err := rows.Scan(
			&i.ID,
			&i.VmID,
			&i.Hostname,
			&i.Hour,
			&i.AmountUusdt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserConversions = `-- name: ListUserConversions :many
SELECT id, amount_ngn_kobo, amount_uusdt, COALESCE(rate::text, '')::text AS rate, status, created_at
FROM conversions WHERE user_id = $1 ORDER BY id DESC LIMIT 10
`

type ListUserConversionsRow struct {
	ID            int64       `json:"id"`
	AmountNgnKobo int64       `json:"amount_ngn_kobo"`
	AmountUusdt   pgtype.Int8 `json:"amount_uusdt"`
	Rate          string      `json:"rate"`
	Status        string      `json:"status"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) ListUserConversions(ctx context.Context, userID int64) ([]ListUserConversionsRow, error) {
	rows, err := q.db.Query(ctx, listUserConversions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserConversionsRow{}
	for rows.Next() {
		var i ListUserConversionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountNgnKobo,
			&i.AmountUusdt,
			&i.Rate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextConversionAttempt = `-- name: NextConversionAttempt :exec
UPDATE conversions SET ispend_quote_id = NULL, convert_attempt = convert_attempt + 1 WHERE id = $1
`

func (q *Queries) NextConversionAttempt(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, nextConversionAttempt, id)
	return err
}

const saveQuote = `-- name: SaveQuote :exec
INSERT INTO conversion_quotes (id, user_id, amount_ngn_kobo, amount_uusdt, rate, expires_at)
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (id) DO NOTHING
`

type SaveQuoteParams struct {
	ID            string             `json:"id"`
	UserID        int64              `json:"user_id"`
	AmountNgnKobo int64              `json:"amount_ngn_kobo"`
	AmountUusdt   int64              `json:"amount_uusdt"`
	Rate          string             `json:"rate"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) SaveQuote(ctx context.Context, arg SaveQuoteParams) error {
	_, err := q.db.Exec(ctx, saveQuote,
		arg.ID,
		arg.UserID,
		arg.AmountNgnKobo,
		arg.AmountUusdt,
		arg.Rate,
		arg.ExpiresAt,
	)
	return err
}

const setConversionError = `-- name: SetConversionError :exec
UPDATE conversions SET last_error = $2 WHERE id = $1
`

type SetConversionErrorParams struct {
	ID        int64       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) SetConversionError(ctx context.Context, arg SetConversionErrorParams) error {
	_, err := q.db.Exec(ctx, setConversionError, arg.ID, arg.LastError)
	return err
}

const setConversionQuote = `-- name: SetConversionQuote :exec
UPDATE conversions SET ispend_quote_id = $2 WHERE id = $1
`

type SetConversionQuoteParams struct {
	ID            int64       `json:"id"`
	IspendQuoteID pgtype.Text `json:"ispend_quote_id"`
}

func (q *Queries) SetConversionQuote(ctx context.Context, arg SetConversionQuoteParams) error {
	_, err := q.db.Exec(ctx, setConversionQuote, arg.ID, arg.IspendQuoteID)
	return err
}

const setVirtualAccount = `-- name: SetVirtualAccount :exec
UPDATE users SET va_bank = $2, va_account_number = $3, va_account_name = $4 WHERE id = $1
`

type SetVirtualAccountParams struct {
	ID              int64       `json:"id"`
	VaBank          pgtype.Text `json:"va_bank"`
	VaAccountNumber pgtype.Text `json:"va_account_number"`
	VaAccountName   pgtype.Text `json:"va_account_name"`
}

func (q *Queries) SetVirtualAccount(ctx context.Context, arg SetVirtualAccountParams) error {
	_, err := q.db.Exec(ctx, setVirtualAccount,
		arg.ID,
		arg.VaBank,
		arg.VaAccountNumber,
		arg.VaAccountName,
	)
	return err
}

const updateAutoConvert = `-- name: UpdateAutoConvert :exec
UPDATE users SET auto_convert = $2 WHERE id = $1
`

type UpdateAutoConvertParams struct {
	ID          int64 `json:"id"`
	AutoConvert bool  `json:"auto_convert"`
}

func (q *Queries) UpdateAutoConvert(ctx context.Context, arg UpdateAutoConvertParams) error {
	_, err := q.db.Exec(ctx, updateAutoConvert, arg.ID, arg.AutoConvert)
	return err
}

const userHourlyRate = `-- name: UserHourlyRate :one
SELECT COALESCE(sum(p.price_uusdt_hourly), 0)::bigint
FROM vms v JOIN plans p ON p.id = v.plan_id
WHERE v.user_id = $1 AND v.billing_from IS NOT NULL AND v.billing_until IS NULL
`

func (q *Queries) UserHourlyRate(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, userHourlyRate, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const userUnpaidTotal = `-- name: UserUnpaidTotal :one
SELECT COALESCE(sum(amount_uusdt), 0)::bigint FROM usage_charges
WHERE user_id = $1 AND status IN ('pending', 'unpaid')
`

func (q *Queries) UserUnpaidTotal(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, userUnpaidTotal, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
