// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalogue.sql

package db

import (
	"context"
)

const listActivePlans = `-- name: ListActivePlans :many
SELECT id, slug, vcpu, ram_mb, disk_gb, price_uusdt_hourly, price_uusdt_monthly_cap
FROM plans WHERE active ORDER BY price_uusdt_hourly
`

type ListActivePlansRow struct {
	ID                   int64  `json:"id"`
	Slug                 string `json:"slug"`
	Vcpu                 int32  `json:"vcpu"`
	RamMb                int32  `json:"ram_mb"`
	DiskGb               int32  `json:"disk_gb"`
	PriceUusdtHourly     int64  `json:"price_uusdt_hourly"`
	PriceUusdtMonthlyCap int64  `json:"price_uusdt_monthly_cap"`
}

func (q *Queries) ListActivePlans(ctx context.Context) ([]ListActivePlansRow, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePlansRow{}
	for rows.Next() {
		var i ListActivePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Vcpu,
			&i.RamMb,
			&i.DiskGb,
			&i.PriceUusdtHourly,
			&i.PriceUusdtMonthlyCap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTemplates = `-- name: ListActiveTemplates :many
SELECT id, slug, name FROM templates WHERE active ORDER BY id
`

type ListActiveTemplatesRow struct {
	ID   int64  `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) ListActiveTemplates(ctx context.Context) ([]ListActiveTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listActiveTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTemplatesRow{}
	for rows.Next() {
		var i ListActiveTemplatesRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
