// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalogue.sql

package db

import (
	"context"
)

const adminListPlans = `-- name: AdminListPlans :many
SELECT p.id, p.slug, p.vcpu, p.ram_mb, p.disk_gb, p.price_uusdt_hourly, p.price_uusdt_monthly_cap, p.active,
       (SELECT count(*) FROM vms v WHERE v.plan_id = p.id AND v.deleted_at IS NULL AND v.state <> 'error')::bigint AS vm_count
FROM plans p ORDER BY p.price_uusdt_hourly, p.id
`

type AdminListPlansRow struct {
	ID                   int64  `json:"id"`
	Slug                 string `json:"slug"`
	Vcpu                 int32  `json:"vcpu"`
	RamMb                int32  `json:"ram_mb"`
	DiskGb               int32  `json:"disk_gb"`
	PriceUusdtHourly     int64  `json:"price_uusdt_hourly"`
	PriceUusdtMonthlyCap int64  `json:"price_uusdt_monthly_cap"`
	Active               bool   `json:"active"`
	VmCount              int64  `json:"vm_count"`
}

// Every plan, active or not, with how many live VMs sit on it and how many are being billed.
func (q *Queries) AdminListPlans(ctx context.Context) ([]AdminListPlansRow, error) {
	rows, err := q.db.Query(ctx, adminListPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListPlansRow{}
	for rows.Next() {
		var i AdminListPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Vcpu,
			&i.RamMb,
			&i.DiskGb,
			&i.PriceUusdtHourly,
			&i.PriceUusdtMonthlyCap,
			&i.Active,
			&i.VmCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListTemplates = `-- name: AdminListTemplates :many
SELECT t.id, t.slug, t.name, t.proxmox_template_id, t.ci_user, t.active,
       (SELECT count(*) FROM vms v WHERE v.template_id = t.id AND v.deleted_at IS NULL)::bigint AS vm_count
FROM templates t ORDER BY t.id
`

type AdminListTemplatesRow struct {
	ID                int64  `json:"id"`
	Slug              string `json:"slug"`
	Name              string `json:"name"`
	ProxmoxTemplateID int32  `json:"proxmox_template_id"`
	CiUser            string `json:"ci_user"`
	Active            bool   `json:"active"`
	VmCount           int64  `json:"vm_count"`
}

func (q *Queries) AdminListTemplates(ctx context.Context) ([]AdminListTemplatesRow, error) {
	rows, err := q.db.Query(ctx, adminListTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListTemplatesRow{}
	for rows.Next() {
		var i AdminListTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ProxmoxTemplateID,
			&i.CiUser,
			&i.Active,
			&i.VmCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBillingVMsOnPlan = `-- name: CountBillingVMsOnPlan :one
SELECT count(*) FROM vms WHERE plan_id = $1 AND billing_from IS NOT NULL AND billing_until IS NULL
`

// VMs whose next hourly charge uses this plan's price.
func (q *Queries) CountBillingVMsOnPlan(ctx context.Context, planID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBillingVMsOnPlan, planID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPlanAny = `-- name: GetPlanAny :one
SELECT id, slug, vcpu, ram_mb, disk_gb, price_uusdt_hourly, price_uusdt_monthly_cap, active FROM plans WHERE slug = $1
`

func (q *Queries) GetPlanAny(ctx context.Context, slug string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanAny, slug)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Vcpu,
		&i.RamMb,
		&i.DiskGb,
		&i.PriceUusdtHourly,
		&i.PriceUusdtMonthlyCap,
		&i.Active,
	)
	return i, err
}

const getTemplateAny = `-- name: GetTemplateAny :one
SELECT id, slug, name, proxmox_template_id, active, ci_user FROM templates WHERE slug = $1
`

func (q *Queries) GetTemplateAny(ctx context.Context, slug string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateAny, slug)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ProxmoxTemplateID,
		&i.Active,
		&i.CiUser,
	)
	return i, err
}

const insertPlan = `-- name: InsertPlan :one
INSERT INTO plans (slug, vcpu, ram_mb, disk_gb, price_uusdt_hourly, price_uusdt_monthly_cap, active)
VALUES ($1, $2, $3, $4, $5, $6, TRUE) RETURNING id, slug, vcpu, ram_mb, disk_gb, price_uusdt_hourly, price_uusdt_monthly_cap, active
`

type InsertPlanParams struct {
	Slug                 string `json:"slug"`
	Vcpu                 int32  `json:"vcpu"`
	RamMb                int32  `json:"ram_mb"`
	DiskGb               int32  `json:"disk_gb"`
	PriceUusdtHourly     int64  `json:"price_uusdt_hourly"`
	PriceUusdtMonthlyCap int64  `json:"price_uusdt_monthly_cap"`
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, insertPlan,
		arg.Slug,
		arg.Vcpu,
		arg.RamMb,
		arg.DiskGb,
		arg.PriceUusdtHourly,
		arg.PriceUusdtMonthlyCap,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Vcpu,
		&i.RamMb,
		&i.DiskGb,
		&i.PriceUusdtHourly,
		&i.PriceUusdtMonthlyCap,
		&i.Active,
	)
	return i, err
}

const insertTemplate = `-- name: InsertTemplate :one
INSERT INTO templates (slug, name, proxmox_template_id, ci_user, active) VALUES ($1, $2, $3, $4, TRUE) RETURNING id, slug, name, proxmox_template_id, active, ci_user
`

type InsertTemplateParams struct {
	Slug              string `json:"slug"`
	Name              string `json:"name"`
	ProxmoxTemplateID int32  `json:"proxmox_template_id"`
	CiUser            string `json:"ci_user"`
}

func (q *Queries) InsertTemplate(ctx context.Context, arg InsertTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, insertTemplate,
		arg.Slug,
		arg.Name,
		arg.ProxmoxTemplateID,
		arg.CiUser,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ProxmoxTemplateID,
		&i.Active,
		&i.CiUser,
	)
	return i, err
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT id, slug, vcpu, ram_mb, disk_gb, price_uusdt_hourly, price_uusdt_monthly_cap
FROM plans WHERE active ORDER BY price_uusdt_hourly
`

type ListActivePlansRow struct {
	ID                   int64  `json:"id"`
	Slug                 string `json:"slug"`
	Vcpu                 int32  `json:"vcpu"`
	RamMb                int32  `json:"ram_mb"`
	DiskGb               int32  `json:"disk_gb"`
	PriceUusdtHourly     int64  `json:"price_uusdt_hourly"`
	PriceUusdtMonthlyCap int64  `json:"price_uusdt_monthly_cap"`
}

func (q *Queries) ListActivePlans(ctx context.Context) ([]ListActivePlansRow, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePlansRow{}
	for rows.Next() {
		var i ListActivePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Vcpu,
			&i.RamMb,
			&i.DiskGb,
			&i.PriceUusdtHourly,
			&i.PriceUusdtMonthlyCap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTemplates = `-- name: ListActiveTemplates :many
SELECT id, slug, name FROM templates WHERE active ORDER BY id
`

type ListActiveTemplatesRow struct {
	ID   int64  `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) ListActiveTemplates(ctx context.Context) ([]ListActiveTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listActiveTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTemplatesRow{}
	for rows.Next() {
		var i ListActiveTemplatesRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlanActive = `-- name: SetPlanActive :exec
UPDATE plans SET active = $2 WHERE id = $1
`

type SetPlanActiveParams struct {
	ID     int64 `json:"id"`
	Active bool  `json:"active"`
}

func (q *Queries) SetPlanActive(ctx context.Context, arg SetPlanActiveParams) error {
	_, err := q.db.Exec(ctx, setPlanActive, arg.ID, arg.Active)
	return err
}

const setPlanPrice = `-- name: SetPlanPrice :exec
UPDATE plans SET price_uusdt_hourly = $2, price_uusdt_monthly_cap = $3 WHERE id = $1
`

type SetPlanPriceParams struct {
	ID                   int64 `json:"id"`
	PriceUusdtHourly     int64 `json:"price_uusdt_hourly"`
	PriceUusdtMonthlyCap int64 `json:"price_uusdt_monthly_cap"`
}

func (q *Queries) SetPlanPrice(ctx context.Context, arg SetPlanPriceParams) error {
	_, err := q.db.Exec(ctx, setPlanPrice, arg.ID, arg.PriceUusdtHourly, arg.PriceUusdtMonthlyCap)
	return err
}

const setTemplateActive = `-- name: SetTemplateActive :exec
UPDATE templates SET active = $2 WHERE id = $1
`

type SetTemplateActiveParams struct {
	ID     int64 `json:"id"`
	Active bool  `json:"active"`
}

func (q *Queries) SetTemplateActive(ctx context.Context, arg SetTemplateActiveParams) error {
	_, err := q.db.Exec(ctx, setTemplateActive, arg.ID, arg.Active)
	return err
}
