// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: closure.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const anonymiseClosedUser = `-- name: AnonymiseClosedUser :exec
UPDATE users SET email = 'closed-' || id || '@invalid', phone = '', password_hash = '!', status = 'closed', closed_at = now(),
       auto_convert = FALSE, email_verified_at = NULL, va_account_name = NULL, va_bank = NULL, va_account_number = NULL
WHERE id = $1 AND status = 'closing'
`

func (q *Queries) AnonymiseClosedUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, anonymiseClosedUser, id)
	return err
}

const beginClosure = `-- name: BeginClosure :execrows
UPDATE users SET status = 'closing', closing_at = now(), purge_after = now() + interval '30 days', auto_convert = FALSE
WHERE id = $1 AND status IN ('active', 'suspended')
`

// Moves an account into its 30-day closing period. Only an account that is not already closing or closed.
func (q *Queries) BeginClosure(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, beginClosure, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserAPITokens = `-- name: DeleteUserAPITokens :exec
DELETE FROM api_tokens WHERE user_id = $1
`

func (q *Queries) DeleteUserAPITokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserAPITokens, userID)
	return err
}

const deleteUserResetRows = `-- name: DeleteUserResetRows :exec
DELETE FROM password_resets WHERE user_id = $1
`

func (q *Queries) DeleteUserResetRows(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserResetRows, userID)
	return err
}

const deleteUserSSHKeys = `-- name: DeleteUserSSHKeys :exec
DELETE FROM ssh_keys WHERE user_id = $1
`

func (q *Queries) DeleteUserSSHKeys(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserSSHKeys, userID)
	return err
}

const deleteUserVerificationRows = `-- name: DeleteUserVerificationRows :exec
DELETE FROM email_verifications WHERE user_id = $1
`

func (q *Queries) DeleteUserVerificationRows(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserVerificationRows, userID)
	return err
}

const exportAdjustments = `-- name: ExportAdjustments :many
SELECT id, amount_uusdt, note, status, created_at FROM adjustments WHERE user_id = $1 ORDER BY id
`

type ExportAdjustmentsRow struct {
	ID          int64     `json:"id"`
	AmountUusdt int64     `json:"amount_uusdt"`
	Note        string    `json:"note"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ExportAdjustments(ctx context.Context, userID int64) ([]ExportAdjustmentsRow, error) {
	rows, err := q.db.Query(ctx, exportAdjustments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportAdjustmentsRow{}
	for rows.Next() {
		var i ExportAdjustmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountUusdt,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportCharges = `-- name: ExportCharges :many
SELECT c.id, COALESCE(c.vm_id, 0)::bigint AS vm_id, COALESCE(c.floating_ip_id, 0)::bigint AS floating_ip_id, c.hour, c.amount_uusdt, c.status FROM usage_charges c WHERE c.user_id = $1 ORDER BY c.hour, c.id
`

type ExportChargesRow struct {
	ID           int64     `json:"id"`
	VmID         int64     `json:"vm_id"`
	FloatingIpID int64     `json:"floating_ip_id"`
	Hour         time.Time `json:"hour"`
	AmountUusdt  int64     `json:"amount_uusdt"`
	Status       string    `json:"status"`
}

func (q *Queries) ExportCharges(ctx context.Context, userID int64) ([]ExportChargesRow, error) {
	rows, err := q.db.Query(ctx, exportCharges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportChargesRow{}
	for rows.Next() {
		var i ExportChargesRow
		if err := rows.Scan(
			&i.ID,
			&i.VmID,
			&i.FloatingIpID,
			&i.Hour,
			&i.AmountUusdt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportConversions = `-- name: ExportConversions :many
SELECT id, amount_ngn_kobo, amount_uusdt, COALESCE(rate::text, '')::text AS rate, status, created_at
FROM conversions WHERE user_id = $1 ORDER BY id
`

type ExportConversionsRow struct {
	ID            int64       `json:"id"`
	AmountNgnKobo int64       `json:"amount_ngn_kobo"`
	AmountUusdt   pgtype.Int8 `json:"amount_uusdt"`
	Rate          string      `json:"rate"`
	Status        string      `json:"status"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) ExportConversions(ctx context.Context, userID int64) ([]ExportConversionsRow, error) {
	rows, err := q.db.Query(ctx, exportConversions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportConversionsRow{}
	for rows.Next() {
		var i ExportConversionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountNgnKobo,
			&i.AmountUusdt,
			&i.Rate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportSSHKeys = `-- name: ExportSSHKeys :many
SELECT name, fingerprint, public_key, created_at FROM ssh_keys WHERE user_id = $1 ORDER BY id
`

type ExportSSHKeysRow struct {
	Name        string    `json:"name"`
	Fingerprint string    `json:"fingerprint"`
	PublicKey   string    `json:"public_key"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ExportSSHKeys(ctx context.Context, userID int64) ([]ExportSSHKeysRow, error) {
	rows, err := q.db.Query(ctx, exportSSHKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportSSHKeysRow{}
	for rows.Next() {
		var i ExportSSHKeysRow
		if err := rows.Scan(
			&i.Name,
			&i.Fingerprint,
			&i.PublicKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportTokens = `-- name: ExportTokens :many
SELECT name, prefix, created_at, last_used_at, expires_at, revoked_at FROM api_tokens WHERE user_id = $1 ORDER BY id
`

type ExportTokensRow struct {
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	CreatedAt  time.Time          `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ExportTokens(ctx context.Context, userID int64) ([]ExportTokensRow, error) {
	rows, err := q.db.Query(ctx, exportTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportTokensRow{}
	for rows.Next() {
		var i ExportTokensRow
		if err := rows.Scan(
			&i.Name,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportVMs = `-- name: ExportVMs :many
SELECT v.id, v.hostname, v.region, p.slug AS plan_slug, t.slug AS template_slug, v.state, v.labels,
       COALESCE(host(ip.address), '')::text AS ipv4, COALESCE(v.ipv6, '')::text AS ipv6, v.created_at, v.deleted_at
FROM vms v JOIN plans p ON p.id = v.plan_id JOIN templates t ON t.id = v.template_id
LEFT JOIN ip_addresses ip ON ip.id = v.ipv4_id
WHERE v.user_id = $1 ORDER BY v.id
`

type ExportVMsRow struct {
	ID           int64              `json:"id"`
	Hostname     string             `json:"hostname"`
	Region       string             `json:"region"`
	PlanSlug     string             `json:"plan_slug"`
	TemplateSlug string             `json:"template_slug"`
	State        string             `json:"state"`
	Labels       []byte             `json:"labels"`
	Ipv4         string             `json:"ipv4"`
	Ipv6         string             `json:"ipv6"`
	CreatedAt    time.Time          `json:"created_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ExportVMs(ctx context.Context, userID int64) ([]ExportVMsRow, error) {
	rows, err := q.db.Query(ctx, exportVMs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportVMsRow{}
	for rows.Next() {
		var i ExportVMsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.Region,
			&i.PlanSlug,
			&i.TemplateSlug,
			&i.State,
			&i.Labels,
			&i.Ipv4,
			&i.Ipv6,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClosedBefore = `-- name: ListClosedBefore :many
SELECT id, closed_at FROM users WHERE status = 'closed' AND closed_at < $1 ORDER BY closed_at
`

type ListClosedBeforeRow struct {
	ID       int64              `json:"id"`
	ClosedAt pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) ListClosedBefore(ctx context.Context, closedAt pgtype.Timestamptz) ([]ListClosedBeforeRow, error) {
	rows, err := q.db.Query(ctx, listClosedBefore, closedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClosedBeforeRow{}
	for rows.Next() {
		var i ListClosedBeforeRow
		if err := rows.Scan(&i.ID, &i.ClosedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClosingDue = `-- name: ListClosingDue :many
SELECT id, email FROM users WHERE status = 'closing' AND purge_after <= $1 ORDER BY purge_after LIMIT 50
`

type ListClosingDueRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) ListClosingDue(ctx context.Context, purgeAfter pgtype.Timestamptz) ([]ListClosingDueRow, error) {
	rows, err := q.db.Query(ctx, listClosingDue, purgeAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClosingDueRow{}
	for rows.Next() {
		var i ListClosingDueRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDeletableVMs = `-- name: ListUserDeletableVMs :many
SELECT id FROM vms WHERE user_id = $1 AND state IN ('pending', 'provisioning', 'running', 'stopped', 'suspended', 'error')
`

// Every VM of the account that still exists on the host or is being built: closing deletes all of them.
func (q *Queries) ListUserDeletableVMs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserDeletableVMs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenAccount = `-- name: ReopenAccount :execrows
UPDATE users SET status = 'active', closing_at = NULL, purge_after = NULL
WHERE id = $1 AND status = 'closing'
`

func (q *Queries) ReopenAccount(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, reopenAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubAuditTarget = `-- name: ScrubAuditTarget :exec
UPDATE admin_audit SET target = $2 WHERE target = $1
`

type ScrubAuditTargetParams struct {
	Target   string `json:"target"`
	Target_2 string `json:"target_2"`
}

// The audit log names accounts by email; after closure it names the anonymised address instead.
func (q *Queries) ScrubAuditTarget(ctx context.Context, arg ScrubAuditTargetParams) error {
	_, err := q.db.Exec(ctx, scrubAuditTarget, arg.Target, arg.Target_2)
	return err
}

const scrubClosedUserVMs = `-- name: ScrubClosedUserVMs :exec
UPDATE vms SET hostname = 'deleted-' || id, labels = '{}', authorized_keys = '', boot_script = NULL, boot_script_output = NULL,
       rebuild_keys = NULL, rebuild_boot_script = NULL
WHERE user_id = $1
`

// Hostnames, labels, keys and script output can identify a person; the rows stay for the charges that point at them.
func (q *Queries) ScrubClosedUserVMs(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, scrubClosedUserVMs, userID)
	return err
}
