// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verifications.sql

package db

import (
	"context"
	"time"
)

const consumeEmailVerification = `-- name: ConsumeEmailVerification :one
DELETE FROM email_verifications
WHERE token_hash = $1 AND expires_at > now()
RETURNING user_id
`

func (q *Queries) ConsumeEmailVerification(ctx context.Context, tokenHash []byte) (int64, error) {
	row := q.db.QueryRow(ctx, consumeEmailVerification, tokenHash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO email_verifications (token_hash, user_id, expires_at) VALUES ($1, $2, $3)
`

type CreateEmailVerificationParams struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, createEmailVerification, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteUserEmailVerifications = `-- name: DeleteUserEmailVerifications :exec
DELETE FROM email_verifications WHERE user_id = $1
`

func (q *Queries) DeleteUserEmailVerifications(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserEmailVerifications, userID)
	return err
}
