// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: floating.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFloatingIP = `-- name: AddFloatingIP :exec
INSERT INTO floating_ips (address, region, host) VALUES ($1::inet, $2, COALESCE(NULLIF($3::text, ''), 'default')) ON CONFLICT (address) DO NOTHING
`

type AddFloatingIPParams struct {
	Column1 netip.Addr `json:"column_1"`
	Region  string     `json:"region"`
	Column3 string     `json:"column_3"`
}

func (q *Queries) AddFloatingIP(ctx context.Context, arg AddFloatingIPParams) error {
	_, err := q.db.Exec(ctx, addFloatingIP, arg.Column1, arg.Region, arg.Column3)
	return err
}

const claimFloatingIP = `-- name: ClaimFloatingIP :one
UPDATE floating_ips SET user_id = $1, label = $2, allocated_at = now(),
       billing_user_id = $1, billing_from = $3, billing_until = NULL
WHERE floating_ips.id = (SELECT p.id FROM floating_ips p WHERE p.region = $4 AND ($5::text = '' OR p.host = $5::text) AND p.user_id IS NULL AND p.billing_from IS NULL AND p.applied_vm_id IS NULL
            ORDER BY p.id LIMIT 1 FOR UPDATE SKIP LOCKED)
RETURNING id, host(address)::text AS address, region, host, user_id, vm_id, label, allocated_at
`

type ClaimFloatingIPParams struct {
	UserID      pgtype.Int8        `json:"user_id"`
	Label       string             `json:"label"`
	BillingFrom pgtype.Timestamptz `json:"billing_from"`
	WantRegion  string             `json:"want_region"`
	WantHost    string             `json:"want_host"`
}

type ClaimFloatingIPRow struct {
	ID          int64              `json:"id"`
	Address     string             `json:"address"`
	Region      string             `json:"region"`
	Host        string             `json:"host"`
	UserID      pgtype.Int8        `json:"user_id"`
	VmID        pgtype.Int8        `json:"vm_id"`
	Label       string             `json:"label"`
	AllocatedAt pgtype.Timestamptz `json:"allocated_at"`
}

// Takes the lowest free address of the region for the account and starts its billing at the top of the hour.
func (q *Queries) ClaimFloatingIP(ctx context.Context, arg ClaimFloatingIPParams) (ClaimFloatingIPRow, error) {
	row := q.db.QueryRow(ctx, claimFloatingIP,
		arg.UserID,
		arg.Label,
		arg.BillingFrom,
		arg.WantRegion,
		arg.WantHost,
	)
	var i ClaimFloatingIPRow
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Region,
		&i.Host,
		&i.UserID,
		&i.VmID,
		&i.Label,
		&i.AllocatedAt,
	)
	return i, err
}

const clearFloatingApplied = `-- name: ClearFloatingApplied :exec
UPDATE floating_ips SET applied_vm_id = NULL WHERE applied_vm_id = $1
`

func (q *Queries) ClearFloatingApplied(ctx context.Context, appliedVmID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, clearFloatingApplied, appliedVmID)
	return err
}

const countUserFloatingIPs = `-- name: CountUserFloatingIPs :one
SELECT count(*) FROM floating_ips WHERE user_id = $1
`

func (q *Queries) CountUserFloatingIPs(ctx context.Context, userID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countUserFloatingIPs, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const detachFloatingFromVM = `-- name: DetachFloatingFromVM :exec
UPDATE floating_ips SET vm_id = NULL WHERE vm_id = $1
`

// A deleted VM takes its floating IPs with it only in the sense that they stop pointing at it; the account keeps (and pays for) them.
func (q *Queries) DetachFloatingFromVM(ctx context.Context, vmID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, detachFloatingFromVM, vmID)
	return err
}

const finishFloatingBilling = `-- name: FinishFloatingBilling :exec
UPDATE floating_ips SET billing_from = NULL, billing_user_id = NULL
WHERE billing_from IS NOT NULL AND billing_until IS NOT NULL
  AND billing_from > date_trunc('hour', billing_until AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
`

func (q *Queries) FinishFloatingBilling(ctx context.Context) error {
	_, err := q.db.Exec(ctx, finishFloatingBilling)
	return err
}

const floatingDueForCheck = `-- name: FloatingDueForCheck :many
SELECT f.id FROM floating_ips f JOIN vms v ON v.id = f.vm_id
WHERE f.vm_id IS NOT NULL AND v.state = 'running' AND (f.applied_vm_id IS DISTINCT FROM f.vm_id OR f.applied_at IS NULL OR f.applied_at < $1)
  AND NOT EXISTS (SELECT 1 FROM jobs j WHERE j.kind = 'vm.floating' AND j.status IN ('queued', 'running') AND j.payload->>'floating_id' = f.id::text)
ORDER BY f.id LIMIT 100
`

// Attached addresses whose VM is running and that have not been confirmed on the guest for an hour.
func (q *Queries) FloatingDueForCheck(ctx context.Context, appliedAt pgtype.Timestamptz) ([]int64, error) {
	rows, err := q.db.Query(ctx, floatingDueForCheck, appliedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const floatingForVM = `-- name: FloatingForVM :many
SELECT id, host(address)::text AS address FROM floating_ips WHERE vm_id = $1 ORDER BY id
`

type FloatingForVMRow struct {
	ID      int64  `json:"id"`
	Address string `json:"address"`
}

// Addresses wanted on this VM (what its firewall set and interface should hold).
func (q *Queries) FloatingForVM(ctx context.Context, vmID pgtype.Int8) ([]FloatingForVMRow, error) {
	rows, err := q.db.Query(ctx, floatingForVM, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FloatingForVMRow{}
	for rows.Next() {
		var i FloatingForVMRow
		if err := rows.Scan(&i.ID, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFloatingForWork = `-- name: GetFloatingForWork :one
SELECT id, host(address)::text AS address, user_id, vm_id, applied_vm_id FROM floating_ips WHERE id = $1
`

type GetFloatingForWorkRow struct {
	ID          int64       `json:"id"`
	Address     string      `json:"address"`
	UserID      pgtype.Int8 `json:"user_id"`
	VmID        pgtype.Int8 `json:"vm_id"`
	AppliedVmID pgtype.Int8 `json:"applied_vm_id"`
}

func (q *Queries) GetFloatingForWork(ctx context.Context, id int64) (GetFloatingForWorkRow, error) {
	row := q.db.QueryRow(ctx, getFloatingForWork, id)
	var i GetFloatingForWorkRow
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.UserID,
		&i.VmID,
		&i.AppliedVmID,
	)
	return i, err
}

const getUserFloatingIP = `-- name: GetUserFloatingIP :one
SELECT id, host(address)::text AS address, region, host, user_id, vm_id, applied_vm_id, label, allocated_at
FROM floating_ips WHERE id = $1 AND user_id = $2
`

type GetUserFloatingIPParams struct {
	ID     int64       `json:"id"`
	UserID pgtype.Int8 `json:"user_id"`
}

type GetUserFloatingIPRow struct {
	ID          int64              `json:"id"`
	Address     string             `json:"address"`
	Region      string             `json:"region"`
	Host        string             `json:"host"`
	UserID      pgtype.Int8        `json:"user_id"`
	VmID        pgtype.Int8        `json:"vm_id"`
	AppliedVmID pgtype.Int8        `json:"applied_vm_id"`
	Label       string             `json:"label"`
	AllocatedAt pgtype.Timestamptz `json:"allocated_at"`
}

func (q *Queries) GetUserFloatingIP(ctx context.Context, arg GetUserFloatingIPParams) (GetUserFloatingIPRow, error) {
	row := q.db.QueryRow(ctx, getUserFloatingIP, arg.ID, arg.UserID)
	var i GetUserFloatingIPRow
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Region,
		&i.Host,
		&i.UserID,
		&i.VmID,
		&i.AppliedVmID,
		&i.Label,
		&i.AllocatedAt,
	)
	return i, err
}

const insertFloatingCharge = `-- name: InsertFloatingCharge :one
INSERT INTO usage_charges (user_id, floating_ip_id, hour, amount_uusdt, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (floating_ip_id, hour) WHERE floating_ip_id IS NOT NULL DO NOTHING
RETURNING id
`

type InsertFloatingChargeParams struct {
	UserID       int64       `json:"user_id"`
	FloatingIpID pgtype.Int8 `json:"floating_ip_id"`
	Hour         time.Time   `json:"hour"`
	AmountUusdt  int64       `json:"amount_uusdt"`
	Status       string      `json:"status"`
}

func (q *Queries) InsertFloatingCharge(ctx context.Context, arg InsertFloatingChargeParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertFloatingCharge,
		arg.UserID,
		arg.FloatingIpID,
		arg.Hour,
		arg.AmountUusdt,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listBillingFloating = `-- name: ListBillingFloating :many
SELECT id, billing_user_id AS user_id, billing_from, billing_until
FROM floating_ips WHERE billing_from IS NOT NULL AND billing_user_id IS NOT NULL ORDER BY id
`

type ListBillingFloatingRow struct {
	ID           int64              `json:"id"`
	UserID       pgtype.Int8        `json:"user_id"`
	BillingFrom  pgtype.Timestamptz `json:"billing_from"`
	BillingUntil pgtype.Timestamptz `json:"billing_until"`
}

func (q *Queries) ListBillingFloating(ctx context.Context) ([]ListBillingFloatingRow, error) {
	rows, err := q.db.Query(ctx, listBillingFloating)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBillingFloatingRow{}
	for rows.Next() {
		var i ListBillingFloatingRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BillingFrom,
			&i.BillingUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFloatingPool = `-- name: ListFloatingPool :many
SELECT f.id, host(f.address)::text AS address, f.region, f.host, f.user_id, f.vm_id, f.label
FROM floating_ips f ORDER BY f.id
`

type ListFloatingPoolRow struct {
	ID      int64       `json:"id"`
	Address string      `json:"address"`
	Region  string      `json:"region"`
	Host    string      `json:"host"`
	UserID  pgtype.Int8 `json:"user_id"`
	VmID    pgtype.Int8 `json:"vm_id"`
	Label   string      `json:"label"`
}

func (q *Queries) ListFloatingPool(ctx context.Context) ([]ListFloatingPoolRow, error) {
	rows, err := q.db.Query(ctx, listFloatingPool)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFloatingPoolRow{}
	for rows.Next() {
		var i ListFloatingPoolRow
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.Region,
			&i.Host,
			&i.UserID,
			&i.VmID,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFloatingIPs = `-- name: ListUserFloatingIPs :many
SELECT id, host(address)::text AS address, region, host, user_id, vm_id, applied_vm_id, label, allocated_at
FROM floating_ips WHERE user_id = $1 ORDER BY id
`

type ListUserFloatingIPsRow struct {
	ID          int64              `json:"id"`
	Address     string             `json:"address"`
	Region      string             `json:"region"`
	Host        string             `json:"host"`
	UserID      pgtype.Int8        `json:"user_id"`
	VmID        pgtype.Int8        `json:"vm_id"`
	AppliedVmID pgtype.Int8        `json:"applied_vm_id"`
	Label       string             `json:"label"`
	AllocatedAt pgtype.Timestamptz `json:"allocated_at"`
}

func (q *Queries) ListUserFloatingIPs(ctx context.Context, userID pgtype.Int8) ([]ListUserFloatingIPsRow, error) {
	rows, err := q.db.Query(ctx, listUserFloatingIPs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserFloatingIPsRow{}
	for rows.Next() {
		var i ListUserFloatingIPsRow
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.Region,
			&i.Host,
			&i.UserID,
			&i.VmID,
			&i.AppliedVmID,
			&i.Label,
			&i.AllocatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFloatingIP = `-- name: LockFloatingIP :one
SELECT id FROM floating_ips WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockFloatingIP(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockFloatingIP, id)
	err := row.Scan(&id)
	return id, err
}

const markFloatingApplied = `-- name: MarkFloatingApplied :exec
UPDATE floating_ips SET applied_vm_id = $2, applied_at = now() WHERE id = $1
`

type MarkFloatingAppliedParams struct {
	ID          int64       `json:"id"`
	AppliedVmID pgtype.Int8 `json:"applied_vm_id"`
}

func (q *Queries) MarkFloatingApplied(ctx context.Context, arg MarkFloatingAppliedParams) error {
	_, err := q.db.Exec(ctx, markFloatingApplied, arg.ID, arg.AppliedVmID)
	return err
}

const releaseFloatingIP = `-- name: ReleaseFloatingIP :execrows
UPDATE floating_ips SET user_id = NULL, vm_id = NULL, label = '', billing_until = $3
WHERE id = $1 AND user_id = $2
`

type ReleaseFloatingIPParams struct {
	ID           int64              `json:"id"`
	UserID       pgtype.Int8        `json:"user_id"`
	BillingUntil pgtype.Timestamptz `json:"billing_until"`
}

// Gives the address back to the pool once the worker has taken it off its VM; billing stops at the end of the
// current hour (the last hour is already charged in advance).
func (q *Queries) ReleaseFloatingIP(ctx context.Context, arg ReleaseFloatingIPParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseFloatingIP, arg.ID, arg.UserID, arg.BillingUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setFloatingBillingFrom = `-- name: SetFloatingBillingFrom :exec
UPDATE floating_ips SET billing_from = $2 WHERE id = $1
`

type SetFloatingBillingFromParams struct {
	ID          int64              `json:"id"`
	BillingFrom pgtype.Timestamptz `json:"billing_from"`
}

func (q *Queries) SetFloatingBillingFrom(ctx context.Context, arg SetFloatingBillingFromParams) error {
	_, err := q.db.Exec(ctx, setFloatingBillingFrom, arg.ID, arg.BillingFrom)
	return err
}

const setFloatingTarget = `-- name: SetFloatingTarget :execrows
UPDATE floating_ips SET vm_id = $3 WHERE id = $1 AND user_id = $2
`

type SetFloatingTargetParams struct {
	ID     int64       `json:"id"`
	UserID pgtype.Int8 `json:"user_id"`
	VmID   pgtype.Int8 `json:"vm_id"`
}

func (q *Queries) SetFloatingTarget(ctx context.Context, arg SetFloatingTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFloatingTarget, arg.ID, arg.UserID, arg.VmID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const statementFloatingCharges = `-- name: StatementFloatingCharges :many
SELECT c.floating_ip_id, host(f.address)::text AS address, c.hour, c.amount_uusdt, c.status
FROM usage_charges c JOIN floating_ips f ON f.id = c.floating_ip_id
WHERE c.user_id = $1 AND c.hour >= $2 AND c.hour < $3
ORDER BY c.floating_ip_id, c.hour
`

type StatementFloatingChargesParams struct {
	UserID int64     `json:"user_id"`
	Hour   time.Time `json:"hour"`
	Hour_2 time.Time `json:"hour_2"`
}

type StatementFloatingChargesRow struct {
	FloatingIpID pgtype.Int8 `json:"floating_ip_id"`
	Address      string      `json:"address"`
	Hour         time.Time   `json:"hour"`
	AmountUusdt  int64       `json:"amount_uusdt"`
	Status       string      `json:"status"`
}

func (q *Queries) StatementFloatingCharges(ctx context.Context, arg StatementFloatingChargesParams) ([]StatementFloatingChargesRow, error) {
	rows, err := q.db.Query(ctx, statementFloatingCharges, arg.UserID, arg.Hour, arg.Hour_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatementFloatingChargesRow{}
	for rows.Next() {
		var i StatementFloatingChargesRow
		if err := rows.Scan(
			&i.FloatingIpID,
			&i.Address,
			&i.Hour,
			&i.AmountUusdt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
