// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hosts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hostCommittedRAM = `-- name: HostCommittedRAM :many
SELECT v.host, COALESCE(sum(p.ram_mb), 0)::bigint AS ram_mb
FROM vms v JOIN plans p ON p.id = v.plan_id
WHERE v.state IN ('pending', 'provisioning', 'running', 'stopped') GROUP BY v.host
`

type HostCommittedRAMRow struct {
	Host  string `json:"host"`
	RamMb int64  `json:"ram_mb"`
}

// RAM promised to live VMs per host, in MB.
func (q *Queries) HostCommittedRAM(ctx context.Context) ([]HostCommittedRAMRow, error) {
	rows, err := q.db.Query(ctx, hostCommittedRAM)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostCommittedRAMRow{}
	for rows.Next() {
		var i HostCommittedRAMRow
		if err := rows.Scan(&i.Host, &i.RamMb); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hostFreeIPs = `-- name: HostFreeIPs :many
SELECT host, count(*)::int AS free FROM ip_addresses WHERE vm_id IS NULL GROUP BY host
`

type HostFreeIPsRow struct {
	Host string `json:"host"`
	Free int32  `json:"free"`
}

func (q *Queries) HostFreeIPs(ctx context.Context) ([]HostFreeIPsRow, error) {
	rows, err := q.db.Query(ctx, hostFreeIPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostFreeIPsRow{}
	for rows.Next() {
		var i HostFreeIPsRow
		if err := rows.Scan(&i.Host, &i.Free); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hostHasTemplate = `-- name: HostHasTemplate :one
SELECT EXISTS (SELECT 1 FROM host_templates WHERE host = $1 AND template_id = $2)
`

type HostHasTemplateParams struct {
	Host       string `json:"host"`
	TemplateID int64  `json:"template_id"`
}

func (q *Queries) HostHasTemplate(ctx context.Context, arg HostHasTemplateParams) (bool, error) {
	row := q.db.QueryRow(ctx, hostHasTemplate, arg.Host, arg.TemplateID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hostOfVMID = `-- name: HostOfVMID :one
SELECT host FROM vms WHERE proxmox_vmid = $1 LIMIT 1
`

func (q *Queries) HostOfVMID(ctx context.Context, proxmoxVmid pgtype.Int4) (string, error) {
	row := q.db.QueryRow(ctx, hostOfVMID, proxmoxVmid)
	var host string
	err := row.Scan(&host)
	return host, err
}

const hostTemplateVMIDInUse = `-- name: HostTemplateVMIDInUse :one
SELECT EXISTS (SELECT 1 FROM host_templates WHERE host = $1 AND proxmox_template_id = $2 AND template_id <> $3)
`

type HostTemplateVMIDInUseParams struct {
	Host              string `json:"host"`
	ProxmoxTemplateID int32  `json:"proxmox_template_id"`
	TemplateID        int64  `json:"template_id"`
}

func (q *Queries) HostTemplateVMIDInUse(ctx context.Context, arg HostTemplateVMIDInUseParams) (bool, error) {
	row := q.db.QueryRow(ctx, hostTemplateVMIDInUse, arg.Host, arg.ProxmoxTemplateID, arg.TemplateID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hostVMCounts = `-- name: HostVMCounts :many
SELECT host, count(*)::int AS vms FROM vms WHERE state NOT IN ('deleted') GROUP BY host
`

type HostVMCountsRow struct {
	Host string `json:"host"`
	Vms  int32  `json:"vms"`
}

func (q *Queries) HostVMCounts(ctx context.Context) ([]HostVMCountsRow, error) {
	rows, err := q.db.Query(ctx, hostVMCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostVMCountsRow{}
	for rows.Next() {
		var i HostVMCountsRow
		if err := rows.Scan(&i.Host, &i.Vms); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostTemplates = `-- name: ListHostTemplates :many
SELECT ht.host, t.slug, t.active, ht.proxmox_template_id FROM host_templates ht JOIN templates t ON t.id = ht.template_id ORDER BY ht.host, t.id
`

type ListHostTemplatesRow struct {
	Host              string `json:"host"`
	Slug              string `json:"slug"`
	Active            bool   `json:"active"`
	ProxmoxTemplateID int32  `json:"proxmox_template_id"`
}

func (q *Queries) ListHostTemplates(ctx context.Context) ([]ListHostTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listHostTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostTemplatesRow{}
	for rows.Next() {
		var i ListHostTemplatesRow
		if err := rows.Scan(
			&i.Host,
			&i.Slug,
			&i.Active,
			&i.ProxmoxTemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHosts = `-- name: ListHosts :many
SELECT name, status FROM hosts ORDER BY name
`

type ListHostsRow struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

func (q *Queries) ListHosts(ctx context.Context) ([]ListHostsRow, error) {
	rows, err := q.db.Query(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostsRow{}
	for rows.Next() {
		var i ListHostsRow
		if err := rows.Scan(&i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHostStatus = `-- name: SetHostStatus :execrows
UPDATE hosts SET status = $2 WHERE name = $1
`

type SetHostStatusParams struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

func (q *Queries) SetHostStatus(ctx context.Context, arg SetHostStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setHostStatus, arg.Name, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setHostTemplate = `-- name: SetHostTemplate :exec
INSERT INTO host_templates (host, template_id, proxmox_template_id) VALUES ($1, $2, $3)
ON CONFLICT (host, template_id) DO UPDATE SET proxmox_template_id = EXCLUDED.proxmox_template_id
`

type SetHostTemplateParams struct {
	Host              string `json:"host"`
	TemplateID        int64  `json:"template_id"`
	ProxmoxTemplateID int32  `json:"proxmox_template_id"`
}

func (q *Queries) SetHostTemplate(ctx context.Context, arg SetHostTemplateParams) error {
	_, err := q.db.Exec(ctx, setHostTemplate, arg.Host, arg.TemplateID, arg.ProxmoxTemplateID)
	return err
}

const spreadGroupHosts = `-- name: SpreadGroupHosts :many
SELECT DISTINCT host FROM vms
WHERE user_id = $1 AND spread_group = $2 AND state NOT IN ('deleted', 'deleting', 'error')
`

type SpreadGroupHostsParams struct {
	UserID      int64       `json:"user_id"`
	SpreadGroup pgtype.Text `json:"spread_group"`
}

// Hosts already holding a live VM of this account's spread group.
func (q *Queries) SpreadGroupHosts(ctx context.Context, arg SpreadGroupHostsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, spreadGroupHosts, arg.UserID, arg.SpreadGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var host string
		if err := rows.Scan(&host); err != nil {
			return nil, err
		}
		items = append(items, host)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncHost = `-- name: SyncHost :exec
INSERT INTO hosts (name) VALUES ($1) ON CONFLICT (name) DO NOTHING
`

func (q *Queries) SyncHost(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, syncHost, name)
	return err
}
