// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metering.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearGrace = `-- name: ClearGrace :exec
UPDATE users SET grace_started_at = NULL WHERE id = $1
`

func (q *Queries) ClearGrace(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearGrace, id)
	return err
}

const finishBilling = `-- name: FinishBilling :exec
UPDATE vms SET billing_from = NULL
WHERE billing_from IS NOT NULL AND billing_until IS NOT NULL
  AND billing_from > date_trunc('hour', billing_until AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
`

func (q *Queries) FinishBilling(ctx context.Context) error {
	_, err := q.db.Exec(ctx, finishBilling)
	return err
}

const insertUsageCharge = `-- name: InsertUsageCharge :one
INSERT INTO usage_charges (user_id, vm_id, hour, amount_uusdt, status)
VALUES ($1, $2::bigint, $3, $4, $5)
ON CONFLICT (vm_id, hour) DO NOTHING
RETURNING id
`

type InsertUsageChargeParams struct {
	UserID      int64     `json:"user_id"`
	VmID        int64     `json:"vm_id"`
	Hour        time.Time `json:"hour"`
	AmountUusdt int64     `json:"amount_uusdt"`
	Status      string    `json:"status"`
}

func (q *Queries) InsertUsageCharge(ctx context.Context, arg InsertUsageChargeParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertUsageCharge,
		arg.UserID,
		arg.VmID,
		arg.Hour,
		arg.AmountUusdt,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listActiveBillingUsers = `-- name: ListActiveBillingUsers :many
SELECT u.id, u.email, u.ispend_customer_id, u.low_balance_notified_at,
       sum(p.price_uusdt_hourly)::bigint AS hourly
FROM vms v JOIN plans p ON p.id = v.plan_id JOIN users u ON u.id = v.user_id
WHERE v.billing_from IS NOT NULL AND v.billing_until IS NULL AND u.grace_started_at IS NULL
GROUP BY u.id
`

type ListActiveBillingUsersRow struct {
	ID                   int64              `json:"id"`
	Email                string             `json:"email"`
	IspendCustomerID     pgtype.Text        `json:"ispend_customer_id"`
	LowBalanceNotifiedAt pgtype.Timestamptz `json:"low_balance_notified_at"`
	Hourly               int64              `json:"hourly"`
}

func (q *Queries) ListActiveBillingUsers(ctx context.Context) ([]ListActiveBillingUsersRow, error) {
	rows, err := q.db.Query(ctx, listActiveBillingUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveBillingUsersRow{}
	for rows.Next() {
		var i ListActiveBillingUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IspendCustomerID,
			&i.LowBalanceNotifiedAt,
			&i.Hourly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingVMs = `-- name: ListBillingVMs :many
SELECT v.id, v.user_id, v.billing_from, v.billing_until, v.created_at,
       p.price_uusdt_hourly, p.price_uusdt_monthly_cap
FROM vms v JOIN plans p ON p.id = v.plan_id
WHERE v.billing_from IS NOT NULL
ORDER BY v.id
`

type ListBillingVMsRow struct {
	ID                   int64              `json:"id"`
	UserID               int64              `json:"user_id"`
	BillingFrom          pgtype.Timestamptz `json:"billing_from"`
	BillingUntil         pgtype.Timestamptz `json:"billing_until"`
	CreatedAt            time.Time          `json:"created_at"`
	PriceUusdtHourly     int64              `json:"price_uusdt_hourly"`
	PriceUusdtMonthlyCap int64              `json:"price_uusdt_monthly_cap"`
}

func (q *Queries) ListBillingVMs(ctx context.Context) ([]ListBillingVMsRow, error) {
	rows, err := q.db.Query(ctx, listBillingVMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBillingVMsRow{}
	for rows.Next() {
		var i ListBillingVMsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BillingFrom,
			&i.BillingUntil,
			&i.CreatedAt,
			&i.PriceUusdtHourly,
			&i.PriceUusdtMonthlyCap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraceUsers = `-- name: ListGraceUsers :many
SELECT id, email, ispend_customer_id, grace_started_at FROM users WHERE grace_started_at IS NOT NULL
`

type ListGraceUsersRow struct {
	ID               int64              `json:"id"`
	Email            string             `json:"email"`
	IspendCustomerID pgtype.Text        `json:"ispend_customer_id"`
	GraceStartedAt   pgtype.Timestamptz `json:"grace_started_at"`
}

func (q *Queries) ListGraceUsers(ctx context.Context) ([]ListGraceUsersRow, error) {
	rows, err := q.db.Query(ctx, listGraceUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGraceUsersRow{}
	for rows.Next() {
		var i ListGraceUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IspendCustomerID,
			&i.GraceStartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraceVMsToSuspend = `-- name: ListGraceVMsToSuspend :many
SELECT v.id FROM vms v JOIN users u ON u.id = v.user_id
WHERE u.grace_started_at IS NOT NULL AND v.state IN ('running', 'stopped')
  AND NOT EXISTS (SELECT 1 FROM jobs j WHERE j.kind = 'vm.suspend' AND j.status IN ('queued', 'running')
                  AND j.payload->>'vm_id' = v.id::text)
`

func (q *Queries) ListGraceVMsToSuspend(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listGraceVMsToSuspend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenCharges = `-- name: ListOpenCharges :many
SELECT c.id, c.user_id, COALESCE(c.vm_id, 0)::bigint AS vm_id, COALESCE(c.floating_ip_id, 0)::bigint AS floating_ip_id, c.hour, c.amount_uusdt, c.status, u.ispend_customer_id
FROM usage_charges c JOIN users u ON u.id = c.user_id
WHERE c.status IN ('pending', 'unpaid')
ORDER BY c.hour, c.id
LIMIT 500
`

type ListOpenChargesRow struct {
	ID               int64       `json:"id"`
	UserID           int64       `json:"user_id"`
	VmID             int64       `json:"vm_id"`
	FloatingIpID     int64       `json:"floating_ip_id"`
	Hour             time.Time   `json:"hour"`
	AmountUusdt      int64       `json:"amount_uusdt"`
	Status           string      `json:"status"`
	IspendCustomerID pgtype.Text `json:"ispend_customer_id"`
}

func (q *Queries) ListOpenCharges(ctx context.Context) ([]ListOpenChargesRow, error) {
	rows, err := q.db.Query(ctx, listOpenCharges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenChargesRow{}
	for rows.Next() {
		var i ListOpenChargesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VmID,
			&i.FloatingIpID,
			&i.Hour,
			&i.AmountUusdt,
			&i.Status,
			&i.IspendCustomerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSuspendedVMs = `-- name: ListUserSuspendedVMs :many
SELECT v.id, p.price_uusdt_hourly
FROM vms v JOIN plans p ON p.id = v.plan_id
WHERE v.user_id = $1 AND v.state = 'suspended'
`

type ListUserSuspendedVMsRow struct {
	ID               int64 `json:"id"`
	PriceUusdtHourly int64 `json:"price_uusdt_hourly"`
}

func (q *Queries) ListUserSuspendedVMs(ctx context.Context, userID int64) ([]ListUserSuspendedVMsRow, error) {
	rows, err := q.db.Query(ctx, listUserSuspendedVMs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSuspendedVMsRow{}
	for rows.Next() {
		var i ListUserSuspendedVMsRow
		if err := rows.Scan(&i.ID, &i.PriceUusdtHourly); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserVMsToDelete = `-- name: ListUserVMsToDelete :many
SELECT v.id FROM vms v
WHERE v.user_id = $1 AND v.state IN ('suspended', 'running', 'stopped')
  AND NOT EXISTS (SELECT 1 FROM jobs j WHERE j.kind = 'vm.delete' AND j.status IN ('queued', 'running')
                  AND j.payload->>'vm_id' = v.id::text)
`

func (q *Queries) ListUserVMsToDelete(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserVMsToDelete, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChargePaid = `-- name: MarkChargePaid :exec
UPDATE usage_charges SET status = 'paid', ispend_movement_id = $2 WHERE id = $1
`

type MarkChargePaidParams struct {
	ID               int64       `json:"id"`
	IspendMovementID pgtype.Text `json:"ispend_movement_id"`
}

func (q *Queries) MarkChargePaid(ctx context.Context, arg MarkChargePaidParams) error {
	_, err := q.db.Exec(ctx, markChargePaid, arg.ID, arg.IspendMovementID)
	return err
}

const markChargeUnpaid = `-- name: MarkChargeUnpaid :exec
UPDATE usage_charges SET status = 'unpaid' WHERE id = $1
`

func (q *Queries) MarkChargeUnpaid(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markChargeUnpaid, id)
	return err
}

const markVMRunning = `-- name: MarkVMRunning :execrows
UPDATE vms SET state = 'running', billing_from = $2, billing_until = NULL
WHERE id = $1 AND state = 'provisioning'
`

type MarkVMRunningParams struct {
	ID          int64              `json:"id"`
	BillingFrom pgtype.Timestamptz `json:"billing_from"`
}

func (q *Queries) MarkVMRunning(ctx context.Context, arg MarkVMRunningParams) (int64, error) {
	result, err := q.db.Exec(ctx, markVMRunning, arg.ID, arg.BillingFrom)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const monthChargedForVM = `-- name: MonthChargedForVM :one
SELECT COALESCE(sum(amount_uusdt), 0)::bigint FROM usage_charges
WHERE vm_id = $1::bigint AND hour >= $2 AND hour < $3 AND status <> 'refunded'
`

type MonthChargedForVMParams struct {
	VmID     int64     `json:"vm_id"`
	HourFrom time.Time `json:"hour_from"`
	HourTo   time.Time `json:"hour_to"`
}

func (q *Queries) MonthChargedForVM(ctx context.Context, arg MonthChargedForVMParams) (int64, error) {
	row := q.db.QueryRow(ctx, monthChargedForVM, arg.VmID, arg.HourFrom, arg.HourTo)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const resumeVM = `-- name: ResumeVM :execrows
UPDATE vms SET state = 'stopped', suspended_at = NULL, billing_from = $2, billing_until = NULL
WHERE id = $1 AND state = 'suspended'
`

type ResumeVMParams struct {
	ID          int64              `json:"id"`
	BillingFrom pgtype.Timestamptz `json:"billing_from"`
}

func (q *Queries) ResumeVM(ctx context.Context, arg ResumeVMParams) (int64, error) {
	result, err := q.db.Exec(ctx, resumeVM, arg.ID, arg.BillingFrom)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBillingFrom = `-- name: SetBillingFrom :exec
UPDATE vms SET billing_from = $2 WHERE id = $1
`

type SetBillingFromParams struct {
	ID          int64              `json:"id"`
	BillingFrom pgtype.Timestamptz `json:"billing_from"`
}

func (q *Queries) SetBillingFrom(ctx context.Context, arg SetBillingFromParams) error {
	_, err := q.db.Exec(ctx, setBillingFrom, arg.ID, arg.BillingFrom)
	return err
}

const setLowBalanceNotified = `-- name: SetLowBalanceNotified :exec
UPDATE users SET low_balance_notified_at = $2 WHERE id = $1
`

type SetLowBalanceNotifiedParams struct {
	ID                   int64              `json:"id"`
	LowBalanceNotifiedAt pgtype.Timestamptz `json:"low_balance_notified_at"`
}

func (q *Queries) SetLowBalanceNotified(ctx context.Context, arg SetLowBalanceNotifiedParams) error {
	_, err := q.db.Exec(ctx, setLowBalanceNotified, arg.ID, arg.LowBalanceNotifiedAt)
	return err
}

const startGrace = `-- name: StartGrace :execrows
UPDATE users SET grace_started_at = $2 WHERE id = $1 AND grace_started_at IS NULL
`

type StartGraceParams struct {
	ID             int64              `json:"id"`
	GraceStartedAt pgtype.Timestamptz `json:"grace_started_at"`
}

func (q *Queries) StartGrace(ctx context.Context, arg StartGraceParams) (int64, error) {
	result, err := q.db.Exec(ctx, startGrace, arg.ID, arg.GraceStartedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stopBilling = `-- name: StopBilling :exec
UPDATE vms SET billing_until = $2 WHERE id = $1 AND billing_from IS NOT NULL AND billing_until IS NULL
`

type StopBillingParams struct {
	ID           int64              `json:"id"`
	BillingUntil pgtype.Timestamptz `json:"billing_until"`
}

func (q *Queries) StopBilling(ctx context.Context, arg StopBillingParams) error {
	_, err := q.db.Exec(ctx, stopBilling, arg.ID, arg.BillingUntil)
	return err
}

const suspendVM = `-- name: SuspendVM :execrows
UPDATE vms SET state = 'suspended', suspended_at = $2, billing_until = $2
WHERE id = $1 AND state IN ('running', 'stopped')
`

type SuspendVMParams struct {
	ID          int64              `json:"id"`
	SuspendedAt pgtype.Timestamptz `json:"suspended_at"`
}

func (q *Queries) SuspendVM(ctx context.Context, arg SuspendVMParams) (int64, error) {
	result, err := q.db.Exec(ctx, suspendVM, arg.ID, arg.SuspendedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userHasLiveVMs = `-- name: UserHasLiveVMs :one
SELECT EXISTS (SELECT 1 FROM vms WHERE user_id = $1
  AND state IN ('pending', 'provisioning', 'running', 'stopped', 'suspended', 'deleting', 'error'))
`

func (q *Queries) UserHasLiveVMs(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, userHasLiveVMs, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
