// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Conversion struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"user_id"`
	IspendQuoteID    pgtype.Text    `json:"ispend_quote_id"`
	AmountNgnKobo    int64          `json:"amount_ngn_kobo"`
	AmountUusdt      pgtype.Int8    `json:"amount_uusdt"`
	Rate             pgtype.Numeric `json:"rate"`
	IspendMovementID pgtype.Text    `json:"ispend_movement_id"`
	DepositEventID   pgtype.Text    `json:"deposit_event_id"`
	Status           string         `json:"status"`
	CreatedAt        time.Time      `json:"created_at"`
}

type EmailVerification struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type IpAddress struct {
	ID      int64       `json:"id"`
	Address netip.Addr  `json:"address"`
	Gateway netip.Addr  `json:"gateway"`
	Region  string      `json:"region"`
	VmID    pgtype.Int8 `json:"vm_id"`
}

type Job struct {
	ID        int64       `json:"id"`
	Kind      string      `json:"kind"`
	Payload   []byte      `json:"payload"`
	Status    string      `json:"status"`
	Attempts  int32       `json:"attempts"`
	RunAfter  time.Time   `json:"run_after"`
	LastError pgtype.Text `json:"last_error"`
	CreatedAt time.Time   `json:"created_at"`
}

type PasswordReset struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Plan struct {
	ID                   int64  `json:"id"`
	Slug                 string `json:"slug"`
	Vcpu                 int32  `json:"vcpu"`
	RamMb                int32  `json:"ram_mb"`
	DiskGb               int32  `json:"disk_gb"`
	PriceUusdtHourly     int64  `json:"price_uusdt_hourly"`
	PriceUusdtMonthlyCap int64  `json:"price_uusdt_monthly_cap"`
	Active               bool   `json:"active"`
}

type Session struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    int64     `json:"user_id"`
	Kind      string    `json:"kind"`
	CsrfToken string    `json:"csrf_token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type SshKey struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Name        string    `json:"name"`
	PublicKey   string    `json:"public_key"`
	Fingerprint string    `json:"fingerprint"`
	CreatedAt   time.Time `json:"created_at"`
}

type Template struct {
	ID                int64  `json:"id"`
	Slug              string `json:"slug"`
	Name              string `json:"name"`
	ProxmoxTemplateID int32  `json:"proxmox_template_id"`
	Active            bool   `json:"active"`
	CiUser            string `json:"ci_user"`
}

type UsageCharge struct {
	ID               int64       `json:"id"`
	UserID           int64       `json:"user_id"`
	VmID             int64       `json:"vm_id"`
	Hour             time.Time   `json:"hour"`
	AmountUusdt      int64       `json:"amount_uusdt"`
	IspendMovementID pgtype.Text `json:"ispend_movement_id"`
	Status           string      `json:"status"`
}

type User struct {
	ID               int64              `json:"id"`
	Email            string             `json:"email"`
	PasswordHash     string             `json:"password_hash"`
	IspendCustomerID pgtype.Text        `json:"ispend_customer_id"`
	EmailVerifiedAt  pgtype.Timestamptz `json:"email_verified_at"`
	Phone            string             `json:"phone"`
	Status           string             `json:"status"`
	IsAdmin          bool               `json:"is_admin"`
	VmLimit          int32              `json:"vm_limit"`
	AutoConvert      bool               `json:"auto_convert"`
	CreatedAt        time.Time          `json:"created_at"`
}

type Vm struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	Region          string             `json:"region"`
	PlanID          int64              `json:"plan_id"`
	TemplateID      int64              `json:"template_id"`
	ProxmoxVmid     pgtype.Int4        `json:"proxmox_vmid"`
	Hostname        string             `json:"hostname"`
	Ipv4ID          pgtype.Int8        `json:"ipv4_id"`
	Ipv6            pgtype.Text        `json:"ipv6"`
	State           string             `json:"state"`
	SuspendedAt     pgtype.Timestamptz `json:"suspended_at"`
	Port25Unblocked bool               `json:"port25_unblocked"`
	CreatedAt       time.Time          `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	AuthorizedKeys  string             `json:"authorized_keys"`
}

type WebhookEvent struct {
	ID         string    `json:"id"`
	ReceivedAt time.Time `json:"received_at"`
}
