// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Adjustment struct {
	ID               int64       `json:"id"`
	AdminID          int64       `json:"admin_id"`
	UserID           int64       `json:"user_id"`
	AmountUusdt      int64       `json:"amount_uusdt"`
	Note             string      `json:"note"`
	IspendMovementID pgtype.Text `json:"ispend_movement_id"`
	Status           string      `json:"status"`
	LastError        pgtype.Text `json:"last_error"`
	CreatedAt        time.Time   `json:"created_at"`
	RequestID        pgtype.Text `json:"request_id"`
}

type AdminAudit struct {
	ID      int64     `json:"id"`
	AdminID int64     `json:"admin_id"`
	Action  string    `json:"action"`
	Target  string    `json:"target"`
	Detail  []byte    `json:"detail"`
	At      time.Time `json:"at"`
}

type AlertsSent struct {
	Key        string    `json:"key"`
	LastSentAt time.Time `json:"last_sent_at"`
}

type ApiToken struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  time.Time          `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Conversion struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"user_id"`
	IspendQuoteID    pgtype.Text    `json:"ispend_quote_id"`
	AmountNgnKobo    int64          `json:"amount_ngn_kobo"`
	AmountUusdt      pgtype.Int8    `json:"amount_uusdt"`
	Rate             pgtype.Numeric `json:"rate"`
	IspendMovementID pgtype.Text    `json:"ispend_movement_id"`
	DepositEventID   pgtype.Text    `json:"deposit_event_id"`
	Status           string         `json:"status"`
	CreatedAt        time.Time      `json:"created_at"`
	LastError        pgtype.Text    `json:"last_error"`
	ConvertAttempt   int32          `json:"convert_attempt"`
}

type ConversionQuote struct {
	ID            string             `json:"id"`
	UserID        int64              `json:"user_id"`
	AmountNgnKobo int64              `json:"amount_ngn_kobo"`
	AmountUusdt   int64              `json:"amount_uusdt"`
	Rate          string             `json:"rate"`
	CreatedAt     time.Time          `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type DepositReversal struct {
	ID            int64       `json:"id"`
	EventKey      string      `json:"event_key"`
	UserID        pgtype.Int8 `json:"user_id"`
	WalletID      string      `json:"wallet_id"`
	AmountKobo    int64       `json:"amount_kobo"`
	UncoveredKobo int64       `json:"uncovered_kobo"`
	OriginalRef   string      `json:"original_ref"`
	CreatedAt     time.Time   `json:"created_at"`
}

type EmailVerification struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Heartbeat struct {
	Name string    `json:"name"`
	At   time.Time `json:"at"`
}

type IpAddress struct {
	ID      int64       `json:"id"`
	Address netip.Addr  `json:"address"`
	Gateway netip.Addr  `json:"gateway"`
	Region  string      `json:"region"`
	VmID    pgtype.Int8 `json:"vm_id"`
}

type Job struct {
	ID        int64              `json:"id"`
	Kind      string             `json:"kind"`
	Payload   []byte             `json:"payload"`
	Status    string             `json:"status"`
	Attempts  int32              `json:"attempts"`
	RunAfter  time.Time          `json:"run_after"`
	LastError pgtype.Text        `json:"last_error"`
	CreatedAt time.Time          `json:"created_at"`
	AlertedAt pgtype.Timestamptz `json:"alerted_at"`
}

type PasswordReset struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Plan struct {
	ID                   int64  `json:"id"`
	Slug                 string `json:"slug"`
	Vcpu                 int32  `json:"vcpu"`
	RamMb                int32  `json:"ram_mb"`
	DiskGb               int32  `json:"disk_gb"`
	PriceUusdtHourly     int64  `json:"price_uusdt_hourly"`
	PriceUusdtMonthlyCap int64  `json:"price_uusdt_monthly_cap"`
	Active               bool   `json:"active"`
}

type Session struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    int64     `json:"user_id"`
	Kind      string    `json:"kind"`
	CsrfToken string    `json:"csrf_token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Snapshot struct {
	ID        int64       `json:"id"`
	VmID      int64       `json:"vm_id"`
	Name      string      `json:"name"`
	PveName   string      `json:"pve_name"`
	Status    string      `json:"status"`
	LastError pgtype.Text `json:"last_error"`
	CreatedAt time.Time   `json:"created_at"`
}

type SshKey struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Name        string    `json:"name"`
	PublicKey   string    `json:"public_key"`
	Fingerprint string    `json:"fingerprint"`
	CreatedAt   time.Time `json:"created_at"`
}

type Template struct {
	ID                int64  `json:"id"`
	Slug              string `json:"slug"`
	Name              string `json:"name"`
	ProxmoxTemplateID int32  `json:"proxmox_template_id"`
	Active            bool   `json:"active"`
	CiUser            string `json:"ci_user"`
}

type UsageCharge struct {
	ID               int64       `json:"id"`
	UserID           int64       `json:"user_id"`
	VmID             int64       `json:"vm_id"`
	Hour             time.Time   `json:"hour"`
	AmountUusdt      int64       `json:"amount_uusdt"`
	IspendMovementID pgtype.Text `json:"ispend_movement_id"`
	Status           string      `json:"status"`
	CreatedAt        time.Time   `json:"created_at"`
}

type User struct {
	ID                   int64              `json:"id"`
	Email                string             `json:"email"`
	PasswordHash         string             `json:"password_hash"`
	IspendCustomerID     pgtype.Text        `json:"ispend_customer_id"`
	EmailVerifiedAt      pgtype.Timestamptz `json:"email_verified_at"`
	Phone                string             `json:"phone"`
	Status               string             `json:"status"`
	IsAdmin              bool               `json:"is_admin"`
	VmLimit              int32              `json:"vm_limit"`
	AutoConvert          bool               `json:"auto_convert"`
	CreatedAt            time.Time          `json:"created_at"`
	GraceStartedAt       pgtype.Timestamptz `json:"grace_started_at"`
	LowBalanceNotifiedAt pgtype.Timestamptz `json:"low_balance_notified_at"`
	AupAcceptedAt        pgtype.Timestamptz `json:"aup_accepted_at"`
	VaBank               pgtype.Text        `json:"va_bank"`
	VaAccountNumber      pgtype.Text        `json:"va_account_number"`
	VaAccountName        pgtype.Text        `json:"va_account_name"`
}

type Vm struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	Region            string             `json:"region"`
	PlanID            int64              `json:"plan_id"`
	TemplateID        int64              `json:"template_id"`
	ProxmoxVmid       pgtype.Int4        `json:"proxmox_vmid"`
	Hostname          string             `json:"hostname"`
	Ipv4ID            pgtype.Int8        `json:"ipv4_id"`
	Ipv6              pgtype.Text        `json:"ipv6"`
	State             string             `json:"state"`
	SuspendedAt       pgtype.Timestamptz `json:"suspended_at"`
	Port25Unblocked   bool               `json:"port25_unblocked"`
	CreatedAt         time.Time          `json:"created_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	AuthorizedKeys    string             `json:"authorized_keys"`
	BillingFrom       pgtype.Timestamptz `json:"billing_from"`
	BillingUntil      pgtype.Timestamptz `json:"billing_until"`
	CpuHighSince      pgtype.Timestamptz `json:"cpu_high_since"`
	FlaggedAt         pgtype.Timestamptz `json:"flagged_at"`
	FlagReason        pgtype.Text        `json:"flag_reason"`
	Busy              pgtype.Text        `json:"busy"`
	ResizePlanID      pgtype.Int8        `json:"resize_plan_id"`
	RebuildTemplateID pgtype.Int8        `json:"rebuild_template_id"`
	RebuildKeys       pgtype.Text        `json:"rebuild_keys"`
	Labels            []byte             `json:"labels"`
	ClientToken       pgtype.Text        `json:"client_token"`
	BootScript        pgtype.Text        `json:"boot_script"`
	BootScriptStatus  string             `json:"boot_script_status"`
	BootScriptExit    pgtype.Int4        `json:"boot_script_exit"`
	BootScriptOutput  pgtype.Text        `json:"boot_script_output"`
	RebuildBootScript pgtype.Text        `json:"rebuild_boot_script"`
}

type WebhookEvent struct {
	ID         string    `json:"id"`
	ReceivedAt time.Time `json:"received_at"`
}

type WebhookFailure struct {
	ID int64     `json:"id"`
	At time.Time `json:"at"`
	Ip string    `json:"ip"`
}
