// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitor.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const banUser = `-- name: BanUser :exec
UPDATE users SET status = 'banned' WHERE email = $1
`

func (q *Queries) BanUser(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, banUser, email)
	return err
}

const claimAlert = `-- name: ClaimAlert :one
INSERT INTO alerts_sent (key, last_sent_at) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET last_sent_at = EXCLUDED.last_sent_at
  WHERE alerts_sent.last_sent_at <= $3
RETURNING key
`

type ClaimAlertParams struct {
	Key          string    `json:"key"`
	LastSentAt   time.Time `json:"last_sent_at"`
	LastSentAt_2 time.Time `json:"last_sent_at_2"`
}

func (q *Queries) ClaimAlert(ctx context.Context, arg ClaimAlertParams) (string, error) {
	row := q.db.QueryRow(ctx, claimAlert, arg.Key, arg.LastSentAt, arg.LastSentAt_2)
	var key string
	err := row.Scan(&key)
	return key, err
}

const clearVMFlag = `-- name: ClearVMFlag :exec
UPDATE vms SET flagged_at = NULL, flag_reason = NULL, cpu_high_since = NULL WHERE id = $1
`

func (q *Queries) ClearVMFlag(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearVMFlag, id)
	return err
}

const committedRAMMB = `-- name: CommittedRAMMB :one
SELECT COALESCE(sum(p.ram_mb), 0)::bigint FROM vms v JOIN plans p ON p.id = v.plan_id
WHERE v.state IN ('pending', 'provisioning', 'running')
`

func (q *Queries) CommittedRAMMB(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, committedRAMMB)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFreeIPs = `-- name: CountFreeIPs :one
SELECT count(*) FROM ip_addresses WHERE vm_id IS NULL
`

func (q *Queries) CountFreeIPs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFreeIPs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStalePendingCharges = `-- name: CountStalePendingCharges :one
SELECT count(*) FROM usage_charges WHERE status = 'pending' AND created_at < $1
`

func (q *Queries) CountStalePendingCharges(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countStalePendingCharges, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStuckConversions = `-- name: CountStuckConversions :one
SELECT count(*) FROM conversions
WHERE (status = 'failed' AND created_at > $1) OR (status = 'pending' AND last_error IS NOT NULL AND created_at < $2)
`

type CountStuckConversionsParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) CountStuckConversions(ctx context.Context, arg CountStuckConversionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStuckConversions, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebhookFailuresSince = `-- name: CountWebhookFailuresSince :one
SELECT count(*) FROM webhook_failures WHERE at >= $1
`

func (q *Queries) CountWebhookFailuresSince(ctx context.Context, at time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookFailuresSince, at)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const flagVM = `-- name: FlagVM :exec
UPDATE vms SET flagged_at = $2, flag_reason = $3 WHERE id = $1 AND flagged_at IS NULL
`

type FlagVMParams struct {
	ID         int64              `json:"id"`
	FlaggedAt  pgtype.Timestamptz `json:"flagged_at"`
	FlagReason pgtype.Text        `json:"flag_reason"`
}

func (q *Queries) FlagVM(ctx context.Context, arg FlagVMParams) error {
	_, err := q.db.Exec(ctx, flagVM, arg.ID, arg.FlaggedAt, arg.FlagReason)
	return err
}

const getHeartbeat = `-- name: GetHeartbeat :one
SELECT at FROM heartbeats WHERE name = $1
`

func (q *Queries) GetHeartbeat(ctx context.Context, name string) (time.Time, error) {
	row := q.db.QueryRow(ctx, getHeartbeat, name)
	var at time.Time
	err := row.Scan(&at)
	return at, err
}

const heartbeat = `-- name: Heartbeat :exec
INSERT INTO heartbeats (name, at) VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET at = EXCLUDED.at
`

type HeartbeatParams struct {
	Name string    `json:"name"`
	At   time.Time `json:"at"`
}

func (q *Queries) Heartbeat(ctx context.Context, arg HeartbeatParams) error {
	_, err := q.db.Exec(ctx, heartbeat, arg.Name, arg.At)
	return err
}

const listFlaggedVMs = `-- name: ListFlaggedVMs :many
SELECT v.id, v.hostname, v.state, v.flagged_at, COALESCE(v.flag_reason, '')::text AS flag_reason, u.email
FROM vms v JOIN users u ON u.id = v.user_id
WHERE v.flagged_at IS NOT NULL AND v.deleted_at IS NULL ORDER BY v.flagged_at
`

type ListFlaggedVMsRow struct {
	ID         int64              `json:"id"`
	Hostname   string             `json:"hostname"`
	State      string             `json:"state"`
	FlaggedAt  pgtype.Timestamptz `json:"flagged_at"`
	FlagReason string             `json:"flag_reason"`
	Email      string             `json:"email"`
}

func (q *Queries) ListFlaggedVMs(ctx context.Context) ([]ListFlaggedVMsRow, error) {
	rows, err := q.db.Query(ctx, listFlaggedVMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFlaggedVMsRow{}
	for rows.Next() {
		var i ListFlaggedVMsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.State,
			&i.FlaggedAt,
			&i.FlagReason,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPort25Unblocked = `-- name: ListPort25Unblocked :many
SELECT COALESCE(host(ip.address), '')::text AS ipv4, COALESCE(v.ipv6, '')::text AS ipv6
FROM vms v LEFT JOIN ip_addresses ip ON ip.id = v.ipv4_id
WHERE v.port25_unblocked AND v.deleted_at IS NULL AND v.state NOT IN ('deleted', 'error')
`

type ListPort25UnblockedRow struct {
	Ipv4 string `json:"ipv4"`
	Ipv6 string `json:"ipv6"`
}

func (q *Queries) ListPort25Unblocked(ctx context.Context) ([]ListPort25UnblockedRow, error) {
	rows, err := q.db.Query(ctx, listPort25Unblocked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPort25UnblockedRow{}
	for rows.Next() {
		var i ListPort25UnblockedRow
		if err := rows.Scan(&i.Ipv4, &i.Ipv6); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningVMsForCPU = `-- name: ListRunningVMsForCPU :many
SELECT id, proxmox_vmid, hostname, cpu_high_since, flagged_at FROM vms
WHERE state = 'running' AND proxmox_vmid IS NOT NULL
`

type ListRunningVMsForCPURow struct {
	ID           int64              `json:"id"`
	ProxmoxVmid  pgtype.Int4        `json:"proxmox_vmid"`
	Hostname     string             `json:"hostname"`
	CpuHighSince pgtype.Timestamptz `json:"cpu_high_since"`
	FlaggedAt    pgtype.Timestamptz `json:"flagged_at"`
}

func (q *Queries) ListRunningVMsForCPU(ctx context.Context) ([]ListRunningVMsForCPURow, error) {
	rows, err := q.db.Query(ctx, listRunningVMsForCPU)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunningVMsForCPURow{}
	for rows.Next() {
		var i ListRunningVMsForCPURow
		if err := rows.Scan(
			&i.ID,
			&i.ProxmoxVmid,
			&i.Hostname,
			&i.CpuHighSince,
			&i.FlaggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnalertedFailedJobs = `-- name: ListUnalertedFailedJobs :many
SELECT id, kind, COALESCE(last_error, '')::text AS last_error FROM jobs
WHERE status = 'failed' AND alerted_at IS NULL ORDER BY id LIMIT 20
`

type ListUnalertedFailedJobsRow struct {
	ID        int64  `json:"id"`
	Kind      string `json:"kind"`
	LastError string `json:"last_error"`
}

func (q *Queries) ListUnalertedFailedJobs(ctx context.Context) ([]ListUnalertedFailedJobsRow, error) {
	rows, err := q.db.Query(ctx, listUnalertedFailedJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnalertedFailedJobsRow{}
	for rows.Next() {
		var i ListUnalertedFailedJobsRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.LastError); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLiveVMIDs = `-- name: ListUserLiveVMIDs :many
SELECT id FROM vms WHERE user_id = $1 AND state IN ('running', 'stopped')
`

func (q *Queries) ListUserLiveVMIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserLiveVMIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAUP = `-- name: MarkAUP :exec
UPDATE users SET aup_accepted_at = $2 WHERE id = $1
`

type MarkAUPParams struct {
	ID            int64              `json:"id"`
	AupAcceptedAt pgtype.Timestamptz `json:"aup_accepted_at"`
}

func (q *Queries) MarkAUP(ctx context.Context, arg MarkAUPParams) error {
	_, err := q.db.Exec(ctx, markAUP, arg.ID, arg.AupAcceptedAt)
	return err
}

const markJobsAlerted = `-- name: MarkJobsAlerted :exec
UPDATE jobs SET alerted_at = $2 WHERE id = ANY($1::bigint[])
`

type MarkJobsAlertedParams struct {
	Column1   []int64            `json:"column_1"`
	AlertedAt pgtype.Timestamptz `json:"alerted_at"`
}

func (q *Queries) MarkJobsAlerted(ctx context.Context, arg MarkJobsAlertedParams) error {
	_, err := q.db.Exec(ctx, markJobsAlerted, arg.Column1, arg.AlertedAt)
	return err
}

const pruneWebhookFailures = `-- name: PruneWebhookFailures :exec
DELETE FROM webhook_failures WHERE at < $1
`

func (q *Queries) PruneWebhookFailures(ctx context.Context, at time.Time) error {
	_, err := q.db.Exec(ctx, pruneWebhookFailures, at)
	return err
}

const recordWebhookFailure = `-- name: RecordWebhookFailure :exec
INSERT INTO webhook_failures (ip) VALUES ($1)
`

func (q *Queries) RecordWebhookFailure(ctx context.Context, ip string) error {
	_, err := q.db.Exec(ctx, recordWebhookFailure, ip)
	return err
}

const setCPUHighSince = `-- name: SetCPUHighSince :exec
UPDATE vms SET cpu_high_since = $2 WHERE id = $1
`

type SetCPUHighSinceParams struct {
	ID           int64              `json:"id"`
	CpuHighSince pgtype.Timestamptz `json:"cpu_high_since"`
}

func (q *Queries) SetCPUHighSince(ctx context.Context, arg SetCPUHighSinceParams) error {
	_, err := q.db.Exec(ctx, setCPUHighSince, arg.ID, arg.CpuHighSince)
	return err
}

const setPort25 = `-- name: SetPort25 :execrows
UPDATE vms SET port25_unblocked = $2 WHERE id = $1 AND deleted_at IS NULL
`

type SetPort25Params struct {
	ID              int64 `json:"id"`
	Port25Unblocked bool  `json:"port25_unblocked"`
}

func (q *Queries) SetPort25(ctx context.Context, arg SetPort25Params) (int64, error) {
	result, err := q.db.Exec(ctx, setPort25, arg.ID, arg.Port25Unblocked)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserStatus = `-- name: SetUserStatus :execrows
UPDATE users SET status = $2 WHERE email = $1
`

type SetUserStatusParams struct {
	Email  string `json:"email"`
	Status string `json:"status"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserStatus, arg.Email, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
