// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: networks.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addVMPrivateIP = `-- name: AddVMPrivateIP :exec
INSERT INTO vm_private_ips (vm_id, network_id, slot, address, state) VALUES ($1, $2, $3, $4::inet, $5)
`

type AddVMPrivateIPParams struct {
	VmID      int64      `json:"vm_id"`
	NetworkID int64      `json:"network_id"`
	Slot      int16      `json:"slot"`
	Column4   netip.Addr `json:"column_4"`
	State     string     `json:"state"`
}

func (q *Queries) AddVMPrivateIP(ctx context.Context, arg AddVMPrivateIPParams) error {
	_, err := q.db.Exec(ctx, addVMPrivateIP,
		arg.VmID,
		arg.NetworkID,
		arg.Slot,
		arg.Column4,
		arg.State,
	)
	return err
}

const countNetworkMembers = `-- name: CountNetworkMembers :one
SELECT count(*) FROM vm_private_ips WHERE network_id = $1
`

func (q *Queries) CountNetworkMembers(ctx context.Context, networkID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countNetworkMembers, networkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserNetworks = `-- name: CountUserNetworks :one
SELECT count(*) FROM private_networks WHERE user_id = $1
`

func (q *Queries) CountUserNetworks(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserNetworks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPrivateNetwork = `-- name: CreatePrivateNetwork :one
INSERT INTO private_networks (user_id, name, cidr, vlan_id) VALUES ($1, $2, $3::text::cidr, $4)
RETURNING id, name, cidr::text AS cidr, vlan_id, host, created_at
`

type CreatePrivateNetworkParams struct {
	UserID  int64  `json:"user_id"`
	Name    string `json:"name"`
	Column3 string `json:"column_3"`
	VlanID  int32  `json:"vlan_id"`
}

type CreatePrivateNetworkRow struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	Cidr      string      `json:"cidr"`
	VlanID    int32       `json:"vlan_id"`
	Host      pgtype.Text `json:"host"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) CreatePrivateNetwork(ctx context.Context, arg CreatePrivateNetworkParams) (CreatePrivateNetworkRow, error) {
	row := q.db.QueryRow(ctx, createPrivateNetwork,
		arg.UserID,
		arg.Name,
		arg.Column3,
		arg.VlanID,
	)
	var i CreatePrivateNetworkRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cidr,
		&i.VlanID,
		&i.Host,
		&i.CreatedAt,
	)
	return i, err
}

const deletePrivateNetwork = `-- name: DeletePrivateNetwork :one
DELETE FROM private_networks n WHERE n.id = $1 AND n.user_id = $2
  AND NOT EXISTS (SELECT 1 FROM vm_private_ips m WHERE m.network_id = n.id)
RETURNING n.cidr::text AS cidr, n.vlan_id
`

type DeletePrivateNetworkParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type DeletePrivateNetworkRow struct {
	Cidr   string `json:"cidr"`
	VlanID int32  `json:"vlan_id"`
}

func (q *Queries) DeletePrivateNetwork(ctx context.Context, arg DeletePrivateNetworkParams) (DeletePrivateNetworkRow, error) {
	row := q.db.QueryRow(ctx, deletePrivateNetwork, arg.ID, arg.UserID)
	var i DeletePrivateNetworkRow
	err := row.Scan(&i.Cidr, &i.VlanID)
	return i, err
}

const deleteVMPrivateIP = `-- name: DeleteVMPrivateIP :exec
DELETE FROM vm_private_ips WHERE vm_id = $1 AND network_id = $2
`

type DeleteVMPrivateIPParams struct {
	VmID      int64 `json:"vm_id"`
	NetworkID int64 `json:"network_id"`
}

func (q *Queries) DeleteVMPrivateIP(ctx context.Context, arg DeleteVMPrivateIPParams) error {
	_, err := q.db.Exec(ctx, deleteVMPrivateIP, arg.VmID, arg.NetworkID)
	return err
}

const deleteVMPrivateIPs = `-- name: DeleteVMPrivateIPs :exec
DELETE FROM vm_private_ips WHERE vm_id = $1
`

func (q *Queries) DeleteVMPrivateIPs(ctx context.Context, vmID int64) error {
	_, err := q.db.Exec(ctx, deleteVMPrivateIPs, vmID)
	return err
}

const getUserNetwork = `-- name: GetUserNetwork :one
SELECT id, name, cidr::text AS cidr, vlan_id, host, created_at FROM private_networks WHERE id = $1 AND user_id = $2
`

type GetUserNetworkParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetUserNetworkRow struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	Cidr      string      `json:"cidr"`
	VlanID    int32       `json:"vlan_id"`
	Host      pgtype.Text `json:"host"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) GetUserNetwork(ctx context.Context, arg GetUserNetworkParams) (GetUserNetworkRow, error) {
	row := q.db.QueryRow(ctx, getUserNetwork, arg.ID, arg.UserID)
	var i GetUserNetworkRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cidr,
		&i.VlanID,
		&i.Host,
		&i.CreatedAt,
	)
	return i, err
}

const listNetworkCIDRsAndVLANs = `-- name: ListNetworkCIDRsAndVLANs :many
SELECT cidr::text AS cidr, vlan_id FROM private_networks
`

type ListNetworkCIDRsAndVLANsRow struct {
	Cidr   string `json:"cidr"`
	VlanID int32  `json:"vlan_id"`
}

func (q *Queries) ListNetworkCIDRsAndVLANs(ctx context.Context) ([]ListNetworkCIDRsAndVLANsRow, error) {
	rows, err := q.db.Query(ctx, listNetworkCIDRsAndVLANs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNetworkCIDRsAndVLANsRow{}
	for rows.Next() {
		var i ListNetworkCIDRsAndVLANsRow
		if err := rows.Scan(&i.Cidr, &i.VlanID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworkMembers = `-- name: ListNetworkMembers :many
SELECT m.vm_id, v.hostname, host(m.address)::text AS address, m.state
FROM vm_private_ips m JOIN vms v ON v.id = m.vm_id WHERE m.network_id = $1 ORDER BY m.address
`

type ListNetworkMembersRow struct {
	VmID     int64  `json:"vm_id"`
	Hostname string `json:"hostname"`
	Address  string `json:"address"`
	State    string `json:"state"`
}

func (q *Queries) ListNetworkMembers(ctx context.Context, networkID int64) ([]ListNetworkMembersRow, error) {
	rows, err := q.db.Query(ctx, listNetworkMembers, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNetworkMembersRow{}
	for rows.Next() {
		var i ListNetworkMembersRow
		if err := rows.Scan(
			&i.VmID,
			&i.Hostname,
			&i.Address,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuarantinedNetworkIDs = `-- name: ListQuarantinedNetworkIDs :many
SELECT cidr::text AS cidr, vlan_id FROM network_quarantine WHERE until > now()
`

type ListQuarantinedNetworkIDsRow struct {
	Cidr   string `json:"cidr"`
	VlanID int32  `json:"vlan_id"`
}

func (q *Queries) ListQuarantinedNetworkIDs(ctx context.Context) ([]ListQuarantinedNetworkIDsRow, error) {
	rows, err := q.db.Query(ctx, listQuarantinedNetworkIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuarantinedNetworkIDsRow{}
	for rows.Next() {
		var i ListQuarantinedNetworkIDsRow
		if err := rows.Scan(&i.Cidr, &i.VlanID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNetworks = `-- name: ListUserNetworks :many
SELECT id, name, cidr::text AS cidr, vlan_id, host, created_at FROM private_networks WHERE user_id = $1 ORDER BY id
`

type ListUserNetworksRow struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	Cidr      string      `json:"cidr"`
	VlanID    int32       `json:"vlan_id"`
	Host      pgtype.Text `json:"host"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) ListUserNetworks(ctx context.Context, userID int64) ([]ListUserNetworksRow, error) {
	rows, err := q.db.Query(ctx, listUserNetworks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserNetworksRow{}
	for rows.Next() {
		var i ListUserNetworksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cidr,
			&i.VlanID,
			&i.Host,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMPrivateIPs = `-- name: ListVMPrivateIPs :many
SELECT m.id, m.network_id, m.slot, host(m.address)::text AS address, m.state, n.name, n.cidr::text AS cidr, n.vlan_id
FROM vm_private_ips m JOIN private_networks n ON n.id = m.network_id
WHERE m.vm_id = $1 ORDER BY m.slot
`

type ListVMPrivateIPsRow struct {
	ID        int64  `json:"id"`
	NetworkID int64  `json:"network_id"`
	Slot      int16  `json:"slot"`
	Address   string `json:"address"`
	State     string `json:"state"`
	Name      string `json:"name"`
	Cidr      string `json:"cidr"`
	VlanID    int32  `json:"vlan_id"`
}

func (q *Queries) ListVMPrivateIPs(ctx context.Context, vmID int64) ([]ListVMPrivateIPsRow, error) {
	rows, err := q.db.Query(ctx, listVMPrivateIPs, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVMPrivateIPsRow{}
	for rows.Next() {
		var i ListVMPrivateIPsRow
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.Slot,
			&i.Address,
			&i.State,
			&i.Name,
			&i.Cidr,
			&i.VlanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNetwork = `-- name: LockNetwork :one
SELECT id, cidr::text AS cidr, vlan_id, host FROM private_networks WHERE id = $1 AND user_id = $2 FOR UPDATE
`

type LockNetworkParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type LockNetworkRow struct {
	ID     int64       `json:"id"`
	Cidr   string      `json:"cidr"`
	VlanID int32       `json:"vlan_id"`
	Host   pgtype.Text `json:"host"`
}

func (q *Queries) LockNetwork(ctx context.Context, arg LockNetworkParams) (LockNetworkRow, error) {
	row := q.db.QueryRow(ctx, lockNetwork, arg.ID, arg.UserID)
	var i LockNetworkRow
	err := row.Scan(
		&i.ID,
		&i.Cidr,
		&i.VlanID,
		&i.Host,
	)
	return i, err
}

const lockNetworkByID = `-- name: LockNetworkByID :one
SELECT id FROM private_networks WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockNetworkByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockNetworkByID, id)
	err := row.Scan(&id)
	return id, err
}

const networkAddressesInUse = `-- name: NetworkAddressesInUse :many
SELECT host(address)::text AS address FROM vm_private_ips WHERE network_id = $1
`

func (q *Queries) NetworkAddressesInUse(ctx context.Context, networkID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, networkAddressesInUse, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const networkIDsOfVM = `-- name: NetworkIDsOfVM :many
SELECT network_id FROM vm_private_ips WHERE vm_id = $1
`

func (q *Queries) NetworkIDsOfVM(ctx context.Context, vmID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, networkIDsOfVM, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var network_id int64
		if err := rows.Scan(&network_id); err != nil {
			return nil, err
		}
		items = append(items, network_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinNetworkHost = `-- name: PinNetworkHost :exec
UPDATE private_networks SET host = $2 WHERE id = $1
`

type PinNetworkHostParams struct {
	ID   int64       `json:"id"`
	Host pgtype.Text `json:"host"`
}

func (q *Queries) PinNetworkHost(ctx context.Context, arg PinNetworkHostParams) error {
	_, err := q.db.Exec(ctx, pinNetworkHost, arg.ID, arg.Host)
	return err
}

const pruneNetworkQuarantine = `-- name: PruneNetworkQuarantine :exec
DELETE FROM network_quarantine WHERE until <= now()
`

func (q *Queries) PruneNetworkQuarantine(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneNetworkQuarantine)
	return err
}

const quarantineNetworkIDs = `-- name: QuarantineNetworkIDs :exec
INSERT INTO network_quarantine (cidr, vlan_id, until) VALUES ($1::text::cidr, $2, $3)
`

type QuarantineNetworkIDsParams struct {
	Column1 string    `json:"column_1"`
	VlanID  int32     `json:"vlan_id"`
	Until   time.Time `json:"until"`
}

func (q *Queries) QuarantineNetworkIDs(ctx context.Context, arg QuarantineNetworkIDsParams) error {
	_, err := q.db.Exec(ctx, quarantineNetworkIDs, arg.Column1, arg.VlanID, arg.Until)
	return err
}

const setVMPrivateIPState = `-- name: SetVMPrivateIPState :exec
UPDATE vm_private_ips SET state = $3 WHERE vm_id = $1 AND network_id = $2
`

type SetVMPrivateIPStateParams struct {
	VmID      int64  `json:"vm_id"`
	NetworkID int64  `json:"network_id"`
	State     string `json:"state"`
}

func (q *Queries) SetVMPrivateIPState(ctx context.Context, arg SetVMPrivateIPStateParams) error {
	_, err := q.db.Exec(ctx, setVMPrivateIPState, arg.VmID, arg.NetworkID, arg.State)
	return err
}

const unpinEmptyNetwork = `-- name: UnpinEmptyNetwork :exec
UPDATE private_networks n SET host = NULL WHERE n.id = $1 AND NOT EXISTS (SELECT 1 FROM vm_private_ips m WHERE m.network_id = n.id)
`

func (q *Queries) UnpinEmptyNetwork(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, unpinEmptyNetwork, id)
	return err
}
