// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_resets.sql

package db

import (
	"context"
	"time"
)

const consumePasswordReset = `-- name: ConsumePasswordReset :one
DELETE FROM password_resets
WHERE token_hash = $1 AND expires_at > now()
RETURNING user_id
`

func (q *Queries) ConsumePasswordReset(ctx context.Context, tokenHash []byte) (int64, error) {
	row := q.db.QueryRow(ctx, consumePasswordReset, tokenHash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_resets (token_hash, user_id, expires_at) VALUES ($1, $2, $3)
`

type CreatePasswordResetParams struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.Exec(ctx, createPasswordReset, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteUserPasswordResets = `-- name: DeleteUserPasswordResets :exec
DELETE FROM password_resets WHERE user_id = $1
`

func (q *Queries) DeleteUserPasswordResets(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserPasswordResets, userID)
	return err
}
