// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, kind, csrf_token, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    int64     `json:"user_id"`
	Kind      string    `json:"kind"`
	CsrfToken string    `json:"csrf_token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.Kind,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT s.token_hash, s.kind, s.csrf_token, s.expires_at, u.id, u.email, u.password_hash, u.ispend_customer_id, u.email_verified_at, u.phone, u.status, u.is_admin, u.vm_limit, u.auto_convert, u.created_at, u.grace_started_at, u.low_balance_notified_at, u.aup_accepted_at, u.va_bank, u.va_account_number, u.va_account_name, u.closing_at, u.purge_after, u.closed_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionUserRow struct {
	TokenHash            []byte             `json:"token_hash"`
	Kind                 string             `json:"kind"`
	CsrfToken            string             `json:"csrf_token"`
	ExpiresAt            time.Time          `json:"expires_at"`
	ID                   int64              `json:"id"`
	Email                string             `json:"email"`
	PasswordHash         string             `json:"password_hash"`
	IspendCustomerID     pgtype.Text        `json:"ispend_customer_id"`
	EmailVerifiedAt      pgtype.Timestamptz `json:"email_verified_at"`
	Phone                string             `json:"phone"`
	Status               string             `json:"status"`
	IsAdmin              bool               `json:"is_admin"`
	VmLimit              int32              `json:"vm_limit"`
	AutoConvert          bool               `json:"auto_convert"`
	CreatedAt            time.Time          `json:"created_at"`
	GraceStartedAt       pgtype.Timestamptz `json:"grace_started_at"`
	LowBalanceNotifiedAt pgtype.Timestamptz `json:"low_balance_notified_at"`
	AupAcceptedAt        pgtype.Timestamptz `json:"aup_accepted_at"`
	VaBank               pgtype.Text        `json:"va_bank"`
	VaAccountNumber      pgtype.Text        `json:"va_account_number"`
	VaAccountName        pgtype.Text        `json:"va_account_name"`
	ClosingAt            pgtype.Timestamptz `json:"closing_at"`
	PurgeAfter           pgtype.Timestamptz `json:"purge_after"`
	ClosedAt             pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.TokenHash,
		&i.Kind,
		&i.CsrfToken,
		&i.ExpiresAt,
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IspendCustomerID,
		&i.EmailVerifiedAt,
		&i.Phone,
		&i.Status,
		&i.IsAdmin,
		&i.VmLimit,
		&i.AutoConvert,
		&i.CreatedAt,
		&i.GraceStartedAt,
		&i.LowBalanceNotifiedAt,
		&i.AupAcceptedAt,
		&i.VaBank,
		&i.VaAccountNumber,
		&i.VaAccountName,
		&i.ClosingAt,
		&i.PurgeAfter,
		&i.ClosedAt,
	)
	return i, err
}
