// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ssh_keys.sql

package db

import (
	"context"
)

const countSSHKeys = `-- name: CountSSHKeys :one
SELECT count(*) FROM ssh_keys WHERE user_id = $1
`

func (q *Queries) CountSSHKeys(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSSHKeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSSHKey = `-- name: CreateSSHKey :one
INSERT INTO ssh_keys (user_id, name, public_key, fingerprint)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, public_key, fingerprint, created_at
`

type CreateSSHKeyParams struct {
	UserID      int64  `json:"user_id"`
	Name        string `json:"name"`
	PublicKey   string `json:"public_key"`
	Fingerprint string `json:"fingerprint"`
}

func (q *Queries) CreateSSHKey(ctx context.Context, arg CreateSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, createSSHKey,
		arg.UserID,
		arg.Name,
		arg.PublicKey,
		arg.Fingerprint,
	)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSSHKey = `-- name: DeleteSSHKey :execrows
DELETE FROM ssh_keys WHERE id = $1 AND user_id = $2
`

type DeleteSSHKeyParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteSSHKey(ctx context.Context, arg DeleteSSHKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSSHKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSSHKeys = `-- name: ListSSHKeys :many
SELECT id, user_id, name, public_key, fingerprint, created_at FROM ssh_keys WHERE user_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListSSHKeys(ctx context.Context, userID int64) ([]SshKey, error) {
	rows, err := q.db.Query(ctx, listSSHKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SshKey{}
	for rows.Next() {
		var i SshKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PublicKey,
			&i.Fingerprint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
