// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: statements.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const statementAdjustments = `-- name: StatementAdjustments :many
SELECT id, amount_uusdt, note, created_at
FROM adjustments WHERE user_id = $1 AND status = 'complete' AND created_at >= $2 AND created_at < $3 ORDER BY id
`

type StatementAdjustmentsParams struct {
	UserID      int64     `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type StatementAdjustmentsRow struct {
	ID          int64     `json:"id"`
	AmountUusdt int64     `json:"amount_uusdt"`
	Note        string    `json:"note"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) StatementAdjustments(ctx context.Context, arg StatementAdjustmentsParams) ([]StatementAdjustmentsRow, error) {
	rows, err := q.db.Query(ctx, statementAdjustments, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatementAdjustmentsRow{}
	for rows.Next() {
		var i StatementAdjustmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountUusdt,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statementCharges = `-- name: StatementCharges :many
SELECT v.id AS vm_id, v.hostname, v.labels, p.slug AS plan_slug, c.hour, c.amount_uusdt, c.status
FROM usage_charges c
JOIN vms v ON v.id = c.vm_id
JOIN plans p ON p.id = v.plan_id
WHERE c.user_id = $1 AND c.hour >= $2 AND c.hour < $3
ORDER BY c.vm_id, c.hour
`

type StatementChargesParams struct {
	UserID int64     `json:"user_id"`
	Hour   time.Time `json:"hour"`
	Hour_2 time.Time `json:"hour_2"`
}

type StatementChargesRow struct {
	VmID        int64     `json:"vm_id"`
	Hostname    string    `json:"hostname"`
	Labels      []byte    `json:"labels"`
	PlanSlug    string    `json:"plan_slug"`
	Hour        time.Time `json:"hour"`
	AmountUusdt int64     `json:"amount_uusdt"`
	Status      string    `json:"status"`
}

// One row per charged hour in [from, to), deleted VMs included.
func (q *Queries) StatementCharges(ctx context.Context, arg StatementChargesParams) ([]StatementChargesRow, error) {
	rows, err := q.db.Query(ctx, statementCharges, arg.UserID, arg.Hour, arg.Hour_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatementChargesRow{}
	for rows.Next() {
		var i StatementChargesRow
		if err := rows.Scan(
			&i.VmID,
			&i.Hostname,
			&i.Labels,
			&i.PlanSlug,
			&i.Hour,
			&i.AmountUusdt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statementConversions = `-- name: StatementConversions :many
SELECT id, amount_ngn_kobo, amount_uusdt, COALESCE(rate::text, '')::text AS rate, created_at
FROM conversions WHERE user_id = $1 AND status = 'complete' AND created_at >= $2 AND created_at < $3 ORDER BY id
`

type StatementConversionsParams struct {
	UserID      int64     `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type StatementConversionsRow struct {
	ID            int64       `json:"id"`
	AmountNgnKobo int64       `json:"amount_ngn_kobo"`
	AmountUusdt   pgtype.Int8 `json:"amount_uusdt"`
	Rate          string      `json:"rate"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) StatementConversions(ctx context.Context, arg StatementConversionsParams) ([]StatementConversionsRow, error) {
	rows, err := q.db.Query(ctx, statementConversions, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatementConversionsRow{}
	for rows.Next() {
		var i StatementConversionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountNgnKobo,
			&i.AmountUusdt,
			&i.Rate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statementMonths = `-- name: StatementMonths :many
SELECT t.month::text AS month FROM (
    SELECT to_char(c.hour AT TIME ZONE 'UTC', 'YYYY-MM') AS month FROM usage_charges c WHERE c.user_id = $1::bigint
    UNION SELECT to_char(v.created_at AT TIME ZONE 'UTC', 'YYYY-MM') FROM conversions v WHERE v.user_id = $1::bigint AND v.status = 'complete'
    UNION SELECT to_char(a.created_at AT TIME ZONE 'UTC', 'YYYY-MM') FROM adjustments a WHERE a.user_id = $1::bigint AND a.status = 'complete'
) t ORDER BY t.month DESC
`

// UTC calendar months in which the account had a charge, a conversion or an adjustment, newest first.
func (q *Queries) StatementMonths(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, statementMonths, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var month string
		if err := rows.Scan(&month); err != nil {
			return nil, err
		}
		items = append(items, month)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statementUnpaid = `-- name: StatementUnpaid :one
SELECT COALESCE(sum(amount_uusdt), 0)::bigint FROM usage_charges WHERE user_id = $1 AND status = 'unpaid'
`

func (q *Queries) StatementUnpaid(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, statementUnpaid, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
