// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, phone)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, ispend_customer_id, email_verified_at, phone, status, is_admin, vm_limit, auto_convert, created_at, grace_started_at, low_balance_notified_at, aup_accepted_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Phone        string `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IspendCustomerID,
		&i.EmailVerifiedAt,
		&i.Phone,
		&i.Status,
		&i.IsAdmin,
		&i.VmLimit,
		&i.AutoConvert,
		&i.CreatedAt,
		&i.GraceStartedAt,
		&i.LowBalanceNotifiedAt,
		&i.AupAcceptedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, ispend_customer_id, email_verified_at, phone, status, is_admin, vm_limit, auto_convert, created_at, grace_started_at, low_balance_notified_at, aup_accepted_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IspendCustomerID,
		&i.EmailVerifiedAt,
		&i.Phone,
		&i.Status,
		&i.IsAdmin,
		&i.VmLimit,
		&i.AutoConvert,
		&i.CreatedAt,
		&i.GraceStartedAt,
		&i.LowBalanceNotifiedAt,
		&i.AupAcceptedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, ispend_customer_id, email_verified_at, phone, status, is_admin, vm_limit, auto_convert, created_at, grace_started_at, low_balance_notified_at, aup_accepted_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IspendCustomerID,
		&i.EmailVerifiedAt,
		&i.Phone,
		&i.Status,
		&i.IsAdmin,
		&i.VmLimit,
		&i.AutoConvert,
		&i.CreatedAt,
		&i.GraceStartedAt,
		&i.LowBalanceNotifiedAt,
		&i.AupAcceptedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = now() WHERE id = $1 AND email_verified_at IS NULL
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const setISpendCustomer = `-- name: SetISpendCustomer :exec
UPDATE users SET ispend_customer_id = $2 WHERE id = $1
`

type SetISpendCustomerParams struct {
	ID               int64       `json:"id"`
	IspendCustomerID pgtype.Text `json:"ispend_customer_id"`
}

func (q *Queries) SetISpendCustomer(ctx context.Context, arg SetISpendCustomerParams) error {
	_, err := q.db.Exec(ctx, setISpendCustomer, arg.ID, arg.IspendCustomerID)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}
