// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vms.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignIP = `-- name: AssignIP :exec
UPDATE ip_addresses SET vm_id = $2 WHERE id = $1
`

type AssignIPParams struct {
	ID   int64       `json:"id"`
	VmID pgtype.Int8 `json:"vm_id"`
}

func (q *Queries) AssignIP(ctx context.Context, arg AssignIPParams) error {
	_, err := q.db.Exec(ctx, assignIP, arg.ID, arg.VmID)
	return err
}

const claimBootScript = `-- name: ClaimBootScript :execrows
UPDATE vms SET boot_script_status = 'running' WHERE id = $1 AND boot_script_status = 'pending'
`

func (q *Queries) ClaimBootScript(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, claimBootScript, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimFreeIP = `-- name: ClaimFreeIP :one
SELECT id, host(address)::text AS address, host(gateway)::text AS gateway
FROM ip_addresses
WHERE vm_id IS NULL AND region = $1 AND host = $2
ORDER BY id
FOR UPDATE SKIP LOCKED
LIMIT 1
`

type ClaimFreeIPParams struct {
	Region string `json:"region"`
	Host   string `json:"host"`
}

type ClaimFreeIPRow struct {
	ID      int64  `json:"id"`
	Address string `json:"address"`
	Gateway string `json:"gateway"`
}

func (q *Queries) ClaimFreeIP(ctx context.Context, arg ClaimFreeIPParams) (ClaimFreeIPRow, error) {
	row := q.db.QueryRow(ctx, claimFreeIP, arg.Region, arg.Host)
	var i ClaimFreeIPRow
	err := row.Scan(&i.ID, &i.Address, &i.Gateway)
	return i, err
}

const claimVMBusy = `-- name: ClaimVMBusy :execrows
UPDATE vms SET busy = $3, resize_plan_id = $4
WHERE id = $1 AND user_id = $2 AND busy IS NULL AND state IN ('running', 'stopped') AND deleted_at IS NULL
`

type ClaimVMBusyParams struct {
	ID           int64       `json:"id"`
	UserID       int64       `json:"user_id"`
	Busy         pgtype.Text `json:"busy"`
	ResizePlanID pgtype.Int8 `json:"resize_plan_id"`
}

// The one-at-a-time claim: succeeds only for the owner's idle running or stopped VM.
func (q *Queries) ClaimVMBusy(ctx context.Context, arg ClaimVMBusyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimVMBusy,
		arg.ID,
		arg.UserID,
		arg.Busy,
		arg.ResizePlanID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimVMRebuild = `-- name: ClaimVMRebuild :execrows
UPDATE vms SET busy = 'rebuilding', rebuild_template_id = $3, rebuild_keys = $4, rebuild_boot_script = $5
WHERE id = $1 AND user_id = $2 AND busy IS NULL AND state IN ('running', 'stopped') AND deleted_at IS NULL
`

type ClaimVMRebuildParams struct {
	ID                int64       `json:"id"`
	UserID            int64       `json:"user_id"`
	RebuildTemplateID pgtype.Int8 `json:"rebuild_template_id"`
	RebuildKeys       pgtype.Text `json:"rebuild_keys"`
	RebuildBootScript pgtype.Text `json:"rebuild_boot_script"`
}

// Claims an idle running or stopped VM for a rebuild and records the template and keys to rebuild with.
func (q *Queries) ClaimVMRebuild(ctx context.Context, arg ClaimVMRebuildParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimVMRebuild,
		arg.ID,
		arg.UserID,
		arg.RebuildTemplateID,
		arg.RebuildKeys,
		arg.RebuildBootScript,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveVMs = `-- name: CountActiveVMs :one
SELECT count(*) FROM vms WHERE user_id = $1 AND state NOT IN ('deleted', 'error')
`

func (q *Queries) CountActiveVMs(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveVMs, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVMSnapshots = `-- name: CountVMSnapshots :one
SELECT count(*) FROM snapshots WHERE vm_id = $1 AND status IN ('creating', 'ready', 'deleting')
`

func (q *Queries) CountVMSnapshots(ctx context.Context, vmID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countVMSnapshots, vmID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (vm_id, name, pve_name) VALUES ($1, $2, 'pending') RETURNING id
`

type CreateSnapshotParams struct {
	VmID int64  `json:"vm_id"`
	Name string `json:"name"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSnapshot, arg.VmID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createVM = `-- name: CreateVM :one
INSERT INTO vms (user_id, region, plan_id, template_id, proxmox_vmid, hostname, authorized_keys,
                 labels, client_token, boot_script, boot_script_status, host, spread_group)
VALUES ($1, $2, $3, $4, nextval('vmid_seq')::int,
        $5, $6, COALESCE($7::jsonb, '{}'::jsonb),
        $8, $9, COALESCE(NULLIF($10::text, ''), 'none'),
        COALESCE(NULLIF($11::text, ''), 'default'), $12)
RETURNING id
`

type CreateVMParams struct {
	UserID           int64       `json:"user_id"`
	Region           string      `json:"region"`
	PlanID           int64       `json:"plan_id"`
	TemplateID       int64       `json:"template_id"`
	Hostname         string      `json:"hostname"`
	AuthorizedKeys   string      `json:"authorized_keys"`
	Labels           []byte      `json:"labels"`
	ClientToken      pgtype.Text `json:"client_token"`
	BootScript       pgtype.Text `json:"boot_script"`
	BootScriptStatus string      `json:"boot_script_status"`
	Host             string      `json:"host"`
	SpreadGroup      pgtype.Text `json:"spread_group"`
}

func (q *Queries) CreateVM(ctx context.Context, arg CreateVMParams) (int64, error) {
	row := q.db.QueryRow(ctx, createVM,
		arg.UserID,
		arg.Region,
		arg.PlanID,
		arg.TemplateID,
		arg.Hostname,
		arg.AuthorizedKeys,
		arg.Labels,
		arg.ClientToken,
		arg.BootScript,
		arg.BootScriptStatus,
		arg.Host,
		arg.SpreadGroup,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSnapshotRow = `-- name: DeleteSnapshotRow :exec
DELETE FROM snapshots WHERE id = $1
`

func (q *Queries) DeleteSnapshotRow(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSnapshotRow, id)
	return err
}

const deleteVMSnapshots = `-- name: DeleteVMSnapshots :exec
DELETE FROM snapshots WHERE vm_id = $1
`

func (q *Queries) DeleteVMSnapshots(ctx context.Context, vmID int64) error {
	_, err := q.db.Exec(ctx, deleteVMSnapshots, vmID)
	return err
}

const finishBootScript = `-- name: FinishBootScript :exec
UPDATE vms SET boot_script_status = $2, boot_script_exit = $3, boot_script_output = $4, boot_script = NULL WHERE id = $1
`

type FinishBootScriptParams struct {
	ID               int64       `json:"id"`
	BootScriptStatus string      `json:"boot_script_status"`
	BootScriptExit   pgtype.Int4 `json:"boot_script_exit"`
	BootScriptOutput pgtype.Text `json:"boot_script_output"`
}

// The script text is erased once it has run: it may carry a one-time registration token.
func (q *Queries) FinishBootScript(ctx context.Context, arg FinishBootScriptParams) error {
	_, err := q.db.Exec(ctx, finishBootScript,
		arg.ID,
		arg.BootScriptStatus,
		arg.BootScriptExit,
		arg.BootScriptOutput,
	)
	return err
}

const finishRebuild = `-- name: FinishRebuild :execrows
UPDATE vms SET template_id = rebuild_template_id, authorized_keys = rebuild_keys, state = 'running',
       boot_script = rebuild_boot_script,
       boot_script_status = CASE WHEN rebuild_boot_script IS NULL THEN 'none' ELSE 'pending' END,
       boot_script_exit = NULL, boot_script_output = NULL,
       rebuild_template_id = NULL, rebuild_keys = NULL, rebuild_boot_script = NULL, busy = NULL
WHERE id = $1 AND busy = 'rebuilding' AND rebuild_template_id IS NOT NULL
`

// The VM now runs the new template; its old snapshots went with the old disk.
func (q *Queries) FinishRebuild(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, finishRebuild, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishResize = `-- name: FinishResize :execrows
UPDATE vms SET plan_id = resize_plan_id, resize_plan_id = NULL, busy = NULL
WHERE id = $1 AND busy = 'resizing' AND resize_plan_id IS NOT NULL
`

func (q *Queries) FinishResize(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, finishResize, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActivePlanBySlug = `-- name: GetActivePlanBySlug :one
SELECT id, slug, vcpu, ram_mb, disk_gb, price_uusdt_hourly, price_uusdt_monthly_cap, active FROM plans WHERE slug = $1 AND active
`

func (q *Queries) GetActivePlanBySlug(ctx context.Context, slug string) (Plan, error) {
	row := q.db.QueryRow(ctx, getActivePlanBySlug, slug)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Vcpu,
		&i.RamMb,
		&i.DiskGb,
		&i.PriceUusdtHourly,
		&i.PriceUusdtMonthlyCap,
		&i.Active,
	)
	return i, err
}

const getActiveTemplateBySlug = `-- name: GetActiveTemplateBySlug :one
SELECT id, slug, name, proxmox_template_id, active, ci_user FROM templates WHERE slug = $1 AND active
`

func (q *Queries) GetActiveTemplateBySlug(ctx context.Context, slug string) (Template, error) {
	row := q.db.QueryRow(ctx, getActiveTemplateBySlug, slug)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ProxmoxTemplateID,
		&i.Active,
		&i.CiUser,
	)
	return i, err
}

const getBootScriptWork = `-- name: GetBootScriptWork :one
SELECT id, state, proxmox_vmid, COALESCE(boot_script, '')::text AS boot_script, boot_script_status FROM vms WHERE id = $1
`

type GetBootScriptWorkRow struct {
	ID               int64       `json:"id"`
	State            string      `json:"state"`
	ProxmoxVmid      pgtype.Int4 `json:"proxmox_vmid"`
	BootScript       string      `json:"boot_script"`
	BootScriptStatus string      `json:"boot_script_status"`
}

func (q *Queries) GetBootScriptWork(ctx context.Context, id int64) (GetBootScriptWorkRow, error) {
	row := q.db.QueryRow(ctx, getBootScriptWork, id)
	var i GetBootScriptWorkRow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.ProxmoxVmid,
		&i.BootScript,
		&i.BootScriptStatus,
	)
	return i, err
}

const getRebuildWork = `-- name: GetRebuildWork :one
SELECT v.id, v.host, v.state, v.busy, v.proxmox_vmid, v.hostname, v.ipv6, v.rebuild_template_id, v.rebuild_keys, v.rebuild_boot_script,
       p.vcpu, p.ram_mb, p.disk_gb,
       COALESCE(ht.proxmox_template_id, t.proxmox_template_id, 0)::int AS template_vmid, COALESCE(t.ci_user, 'root')::text AS ci_user,
       COALESCE(host(ip.address), '')::text AS ipv4, COALESCE(host(ip.gateway), '')::text AS gateway
FROM vms v
JOIN plans p ON p.id = v.plan_id
LEFT JOIN templates t ON t.id = v.rebuild_template_id
LEFT JOIN host_templates ht ON ht.template_id = t.id AND ht.host = v.host
LEFT JOIN ip_addresses ip ON ip.id = v.ipv4_id
WHERE v.id = $1
`

type GetRebuildWorkRow struct {
	ID                int64       `json:"id"`
	Host              string      `json:"host"`
	State             string      `json:"state"`
	Busy              pgtype.Text `json:"busy"`
	ProxmoxVmid       pgtype.Int4 `json:"proxmox_vmid"`
	Hostname          string      `json:"hostname"`
	Ipv6              pgtype.Text `json:"ipv6"`
	RebuildTemplateID pgtype.Int8 `json:"rebuild_template_id"`
	RebuildKeys       pgtype.Text `json:"rebuild_keys"`
	RebuildBootScript pgtype.Text `json:"rebuild_boot_script"`
	Vcpu              int32       `json:"vcpu"`
	RamMb             int32       `json:"ram_mb"`
	DiskGb            int32       `json:"disk_gb"`
	TemplateVmid      int32       `json:"template_vmid"`
	CiUser            string      `json:"ci_user"`
	Ipv4              string      `json:"ipv4"`
	Gateway           string      `json:"gateway"`
}

func (q *Queries) GetRebuildWork(ctx context.Context, id int64) (GetRebuildWorkRow, error) {
	row := q.db.QueryRow(ctx, getRebuildWork, id)
	var i GetRebuildWorkRow
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.State,
		&i.Busy,
		&i.ProxmoxVmid,
		&i.Hostname,
		&i.Ipv6,
		&i.RebuildTemplateID,
		&i.RebuildKeys,
		&i.RebuildBootScript,
		&i.Vcpu,
		&i.RamMb,
		&i.DiskGb,
		&i.TemplateVmid,
		&i.CiUser,
		&i.Ipv4,
		&i.Gateway,
	)
	return i, err
}

const getResizeWork = `-- name: GetResizeWork :one
SELECT v.id, v.host, v.state, v.busy, v.proxmox_vmid, v.resize_plan_id,
       np.vcpu AS new_vcpu, np.ram_mb AS new_ram_mb, np.disk_gb AS new_disk_gb
FROM vms v LEFT JOIN plans np ON np.id = v.resize_plan_id
WHERE v.id = $1
`

type GetResizeWorkRow struct {
	ID           int64       `json:"id"`
	Host         string      `json:"host"`
	State        string      `json:"state"`
	Busy         pgtype.Text `json:"busy"`
	ProxmoxVmid  pgtype.Int4 `json:"proxmox_vmid"`
	ResizePlanID pgtype.Int8 `json:"resize_plan_id"`
	NewVcpu      pgtype.Int4 `json:"new_vcpu"`
	NewRamMb     pgtype.Int4 `json:"new_ram_mb"`
	NewDiskGb    pgtype.Int4 `json:"new_disk_gb"`
}

func (q *Queries) GetResizeWork(ctx context.Context, id int64) (GetResizeWorkRow, error) {
	row := q.db.QueryRow(ctx, getResizeWork, id)
	var i GetResizeWorkRow
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.State,
		&i.Busy,
		&i.ProxmoxVmid,
		&i.ResizePlanID,
		&i.NewVcpu,
		&i.NewRamMb,
		&i.NewDiskGb,
	)
	return i, err
}

const getSSHKeysByIDs = `-- name: GetSSHKeysByIDs :many
SELECT public_key FROM ssh_keys WHERE user_id = $1 AND id = ANY($2::bigint[]) ORDER BY id
`

type GetSSHKeysByIDsParams struct {
	UserID  int64   `json:"user_id"`
	Column2 []int64 `json:"column_2"`
}

func (q *Queries) GetSSHKeysByIDs(ctx context.Context, arg GetSSHKeysByIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getSSHKeysByIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var public_key string
		if err := rows.Scan(&public_key); err != nil {
			return nil, err
		}
		items = append(items, public_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVM = `-- name: GetUserVM :one
SELECT v.id, v.region, v.host, v.spread_group, v.hostname, v.state, v.ipv6, v.created_at, v.busy, v.resize_plan_id, v.labels, v.boot_script_status, v.boot_script_exit, v.boot_script_output,
       p.slug AS plan_slug, p.price_uusdt_hourly, p.id AS plan_id, p.vcpu, p.ram_mb, p.disk_gb,
       t.slug AS template_slug, t.ci_user,
       COALESCE(host(ip.address), '')::text AS ipv4
FROM vms v
JOIN plans p ON p.id = v.plan_id
JOIN templates t ON t.id = v.template_id
LEFT JOIN ip_addresses ip ON ip.id = v.ipv4_id
WHERE v.id = $1 AND v.user_id = $2 AND v.deleted_at IS NULL
`

type GetUserVMParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetUserVMRow struct {
	ID               int64       `json:"id"`
	Region           string      `json:"region"`
	Host             string      `json:"host"`
	SpreadGroup      pgtype.Text `json:"spread_group"`
	Hostname         string      `json:"hostname"`
	State            string      `json:"state"`
	Ipv6             pgtype.Text `json:"ipv6"`
	CreatedAt        time.Time   `json:"created_at"`
	Busy             pgtype.Text `json:"busy"`
	ResizePlanID     pgtype.Int8 `json:"resize_plan_id"`
	Labels           []byte      `json:"labels"`
	BootScriptStatus string      `json:"boot_script_status"`
	BootScriptExit   pgtype.Int4 `json:"boot_script_exit"`
	BootScriptOutput pgtype.Text `json:"boot_script_output"`
	PlanSlug         string      `json:"plan_slug"`
	PriceUusdtHourly int64       `json:"price_uusdt_hourly"`
	PlanID           int64       `json:"plan_id"`
	Vcpu             int32       `json:"vcpu"`
	RamMb            int32       `json:"ram_mb"`
	DiskGb           int32       `json:"disk_gb"`
	TemplateSlug     string      `json:"template_slug"`
	CiUser           string      `json:"ci_user"`
	Ipv4             string      `json:"ipv4"`
}

func (q *Queries) GetUserVM(ctx context.Context, arg GetUserVMParams) (GetUserVMRow, error) {
	row := q.db.QueryRow(ctx, getUserVM, arg.ID, arg.UserID)
	var i GetUserVMRow
	err := row.Scan(
		&i.ID,
		&i.Region,
		&i.Host,
		&i.SpreadGroup,
		&i.Hostname,
		&i.State,
		&i.Ipv6,
		&i.CreatedAt,
		&i.Busy,
		&i.ResizePlanID,
		&i.Labels,
		&i.BootScriptStatus,
		&i.BootScriptExit,
		&i.BootScriptOutput,
		&i.PlanSlug,
		&i.PriceUusdtHourly,
		&i.PlanID,
		&i.Vcpu,
		&i.RamMb,
		&i.DiskGb,
		&i.TemplateSlug,
		&i.CiUser,
		&i.Ipv4,
	)
	return i, err
}

const getVMByClientToken = `-- name: GetVMByClientToken :one
SELECT v.id, v.hostname, p.slug AS plan_slug, t.slug AS template_slug
FROM vms v JOIN plans p ON p.id = v.plan_id JOIN templates t ON t.id = v.template_id
WHERE v.user_id = $1 AND v.client_token = $2
`

type GetVMByClientTokenParams struct {
	UserID      int64       `json:"user_id"`
	ClientToken pgtype.Text `json:"client_token"`
}

type GetVMByClientTokenRow struct {
	ID           int64  `json:"id"`
	Hostname     string `json:"hostname"`
	PlanSlug     string `json:"plan_slug"`
	TemplateSlug string `json:"template_slug"`
}

func (q *Queries) GetVMByClientToken(ctx context.Context, arg GetVMByClientTokenParams) (GetVMByClientTokenRow, error) {
	row := q.db.QueryRow(ctx, getVMByClientToken, arg.UserID, arg.ClientToken)
	var i GetVMByClientTokenRow
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.PlanSlug,
		&i.TemplateSlug,
	)
	return i, err
}

const getVMForWork = `-- name: GetVMForWork :one
SELECT v.id, v.user_id, v.host, v.hostname, v.state, v.proxmox_vmid, v.authorized_keys, v.ipv6, v.ipv4_id, v.boot_script_status,
       p.vcpu, p.ram_mb, p.disk_gb,
       COALESCE(ht.proxmox_template_id, t.proxmox_template_id)::int AS proxmox_template_id, t.ci_user,
       COALESCE(host(ip.address), '')::text AS ipv4,
       COALESCE(host(ip.gateway), '')::text AS gateway
FROM vms v
JOIN plans p ON p.id = v.plan_id
JOIN templates t ON t.id = v.template_id
LEFT JOIN host_templates ht ON ht.template_id = t.id AND ht.host = v.host
LEFT JOIN ip_addresses ip ON ip.id = v.ipv4_id
WHERE v.id = $1
`

type GetVMForWorkRow struct {
	ID                int64       `json:"id"`
	UserID            int64       `json:"user_id"`
	Host              string      `json:"host"`
	Hostname          string      `json:"hostname"`
	State             string      `json:"state"`
	ProxmoxVmid       pgtype.Int4 `json:"proxmox_vmid"`
	AuthorizedKeys    string      `json:"authorized_keys"`
	Ipv6              pgtype.Text `json:"ipv6"`
	Ipv4ID            pgtype.Int8 `json:"ipv4_id"`
	BootScriptStatus  string      `json:"boot_script_status"`
	Vcpu              int32       `json:"vcpu"`
	RamMb             int32       `json:"ram_mb"`
	DiskGb            int32       `json:"disk_gb"`
	ProxmoxTemplateID int32       `json:"proxmox_template_id"`
	CiUser            string      `json:"ci_user"`
	Ipv4              string      `json:"ipv4"`
	Gateway           string      `json:"gateway"`
}

func (q *Queries) GetVMForWork(ctx context.Context, id int64) (GetVMForWorkRow, error) {
	row := q.db.QueryRow(ctx, getVMForWork, id)
	var i GetVMForWorkRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Host,
		&i.Hostname,
		&i.State,
		&i.ProxmoxVmid,
		&i.AuthorizedKeys,
		&i.Ipv6,
		&i.Ipv4ID,
		&i.BootScriptStatus,
		&i.Vcpu,
		&i.RamMb,
		&i.DiskGb,
		&i.ProxmoxTemplateID,
		&i.CiUser,
		&i.Ipv4,
		&i.Gateway,
	)
	return i, err
}

const getVMSnapshot = `-- name: GetVMSnapshot :one
SELECT id, vm_id, name, pve_name, status FROM snapshots WHERE id = $1 AND vm_id = $2
`

type GetVMSnapshotParams struct {
	ID   int64 `json:"id"`
	VmID int64 `json:"vm_id"`
}

type GetVMSnapshotRow struct {
	ID      int64  `json:"id"`
	VmID    int64  `json:"vm_id"`
	Name    string `json:"name"`
	PveName string `json:"pve_name"`
	Status  string `json:"status"`
}

func (q *Queries) GetVMSnapshot(ctx context.Context, arg GetVMSnapshotParams) (GetVMSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getVMSnapshot, arg.ID, arg.VmID)
	var i GetVMSnapshotRow
	err := row.Scan(
		&i.ID,
		&i.VmID,
		&i.Name,
		&i.PveName,
		&i.Status,
	)
	return i, err
}

const listUserVMs = `-- name: ListUserVMs :many
SELECT v.id, v.region, v.host, v.spread_group, v.hostname, v.state, v.ipv6, v.created_at, v.busy, v.resize_plan_id, v.labels, v.boot_script_status, v.boot_script_exit, v.boot_script_output,
       p.slug AS plan_slug, p.price_uusdt_hourly, p.id AS plan_id, p.vcpu, p.ram_mb, p.disk_gb,
       t.slug AS template_slug, t.ci_user,
       COALESCE(host(ip.address), '')::text AS ipv4
FROM vms v
JOIN plans p ON p.id = v.plan_id
JOIN templates t ON t.id = v.template_id
LEFT JOIN ip_addresses ip ON ip.id = v.ipv4_id
WHERE v.user_id = $1 AND v.deleted_at IS NULL
ORDER BY v.id DESC
`

type ListUserVMsRow struct {
	ID               int64       `json:"id"`
	Region           string      `json:"region"`
	Host             string      `json:"host"`
	SpreadGroup      pgtype.Text `json:"spread_group"`
	Hostname         string      `json:"hostname"`
	State            string      `json:"state"`
	Ipv6             pgtype.Text `json:"ipv6"`
	CreatedAt        time.Time   `json:"created_at"`
	Busy             pgtype.Text `json:"busy"`
	ResizePlanID     pgtype.Int8 `json:"resize_plan_id"`
	Labels           []byte      `json:"labels"`
	BootScriptStatus string      `json:"boot_script_status"`
	BootScriptExit   pgtype.Int4 `json:"boot_script_exit"`
	BootScriptOutput pgtype.Text `json:"boot_script_output"`
	PlanSlug         string      `json:"plan_slug"`
	PriceUusdtHourly int64       `json:"price_uusdt_hourly"`
	PlanID           int64       `json:"plan_id"`
	Vcpu             int32       `json:"vcpu"`
	RamMb            int32       `json:"ram_mb"`
	DiskGb           int32       `json:"disk_gb"`
	TemplateSlug     string      `json:"template_slug"`
	CiUser           string      `json:"ci_user"`
	Ipv4             string      `json:"ipv4"`
}

func (q *Queries) ListUserVMs(ctx context.Context, userID int64) ([]ListUserVMsRow, error) {
	rows, err := q.db.Query(ctx, listUserVMs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserVMsRow{}
	for rows.Next() {
		var i ListUserVMsRow
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.Host,
			&i.SpreadGroup,
			&i.Hostname,
			&i.State,
			&i.Ipv6,
			&i.CreatedAt,
			&i.Busy,
			&i.ResizePlanID,
			&i.Labels,
			&i.BootScriptStatus,
			&i.BootScriptExit,
			&i.BootScriptOutput,
			&i.PlanSlug,
			&i.PriceUusdtHourly,
			&i.PlanID,
			&i.Vcpu,
			&i.RamMb,
			&i.DiskGb,
			&i.TemplateSlug,
			&i.CiUser,
			&i.Ipv4,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMSnapshots = `-- name: ListVMSnapshots :many
SELECT id, vm_id, name, pve_name, status, COALESCE(last_error, '')::text AS last_error, created_at
FROM snapshots WHERE vm_id = $1 AND status <> 'error' ORDER BY id DESC
`

type ListVMSnapshotsRow struct {
	ID        int64     `json:"id"`
	VmID      int64     `json:"vm_id"`
	Name      string    `json:"name"`
	PveName   string    `json:"pve_name"`
	Status    string    `json:"status"`
	LastError string    `json:"last_error"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListVMSnapshots(ctx context.Context, vmID int64) ([]ListVMSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listVMSnapshots, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVMSnapshotsRow{}
	for rows.Next() {
		var i ListVMSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.VmID,
			&i.Name,
			&i.PveName,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	err := row.Scan(&id)
	return id, err
}

const lockUserStatus = `-- name: LockUserStatus :one
SELECT status FROM users WHERE id = $1 FOR UPDATE
`

// Takes the row lock that serialises creating VMs, closing the account and converting deposits.
func (q *Queries) LockUserStatus(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, lockUserStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const markVMDeleted = `-- name: MarkVMDeleted :exec
UPDATE vms SET state = 'deleted', deleted_at = now() WHERE id = $1
`

func (q *Queries) MarkVMDeleted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markVMDeleted, id)
	return err
}

const markVMError = `-- name: MarkVMError :exec
UPDATE vms SET state = 'error', busy = NULL, rebuild_template_id = NULL, rebuild_keys = NULL, rebuild_boot_script = NULL WHERE id = $1
`

func (q *Queries) MarkVMError(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markVMError, id)
	return err
}

const releaseIPForVM = `-- name: ReleaseIPForVM :exec
UPDATE ip_addresses SET vm_id = NULL WHERE vm_id = $1
`

func (q *Queries) ReleaseIPForVM(ctx context.Context, vmID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, releaseIPForVM, vmID)
	return err
}

const releaseVMBusy = `-- name: ReleaseVMBusy :exec
UPDATE vms SET busy = NULL, resize_plan_id = NULL, rebuild_template_id = NULL, rebuild_keys = NULL, rebuild_boot_script = NULL WHERE id = $1
`

func (q *Queries) ReleaseVMBusy(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, releaseVMBusy, id)
	return err
}

const revertBootScript = `-- name: RevertBootScript :exec
UPDATE vms SET boot_script_status = 'pending' WHERE id = $1 AND boot_script_status = 'running'
`

func (q *Queries) RevertBootScript(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revertBootScript, id)
	return err
}

const setSnapshotPVEName = `-- name: SetSnapshotPVEName :exec
UPDATE snapshots SET pve_name = $2 WHERE id = $1
`

type SetSnapshotPVENameParams struct {
	ID      int64  `json:"id"`
	PveName string `json:"pve_name"`
}

func (q *Queries) SetSnapshotPVEName(ctx context.Context, arg SetSnapshotPVENameParams) error {
	_, err := q.db.Exec(ctx, setSnapshotPVEName, arg.ID, arg.PveName)
	return err
}

const setSnapshotStatus = `-- name: SetSnapshotStatus :exec
UPDATE snapshots SET status = $2, last_error = $3 WHERE id = $1
`

type SetSnapshotStatusParams struct {
	ID        int64       `json:"id"`
	Status    string      `json:"status"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) SetSnapshotStatus(ctx context.Context, arg SetSnapshotStatusParams) error {
	_, err := q.db.Exec(ctx, setSnapshotStatus, arg.ID, arg.Status, arg.LastError)
	return err
}

const setVMIPv4 = `-- name: SetVMIPv4 :exec
UPDATE vms SET ipv4_id = $2 WHERE id = $1
`

type SetVMIPv4Params struct {
	ID     int64       `json:"id"`
	Ipv4ID pgtype.Int8 `json:"ipv4_id"`
}

func (q *Queries) SetVMIPv4(ctx context.Context, arg SetVMIPv4Params) error {
	_, err := q.db.Exec(ctx, setVMIPv4, arg.ID, arg.Ipv4ID)
	return err
}

const setVMIPv6 = `-- name: SetVMIPv6 :exec
UPDATE vms SET ipv6 = $2 WHERE id = $1
`

type SetVMIPv6Params struct {
	ID   int64       `json:"id"`
	Ipv6 pgtype.Text `json:"ipv6"`
}

func (q *Queries) SetVMIPv6(ctx context.Context, arg SetVMIPv6Params) error {
	_, err := q.db.Exec(ctx, setVMIPv6, arg.ID, arg.Ipv6)
	return err
}

const setVMLabels = `-- name: SetVMLabels :execrows
UPDATE vms SET labels = $3 WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SetVMLabelsParams struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Labels []byte `json:"labels"`
}

func (q *Queries) SetVMLabels(ctx context.Context, arg SetVMLabelsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVMLabels, arg.ID, arg.UserID, arg.Labels)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumActiveHourly = `-- name: SumActiveHourly :one
SELECT COALESCE(sum(p.price_uusdt_hourly), 0)::bigint
FROM vms v JOIN plans p ON p.id = v.plan_id
WHERE v.user_id = $1 AND v.state NOT IN ('deleted', 'error')
`

func (q *Queries) SumActiveHourly(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumActiveHourly, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const transitionVM = `-- name: TransitionVM :execrows
UPDATE vms SET state = $3 WHERE id = $1 AND state = ANY($2::text[])
`

type TransitionVMParams struct {
	ID      int64    `json:"id"`
	Column2 []string `json:"column_2"`
	State   string   `json:"state"`
}

func (q *Queries) TransitionVM(ctx context.Context, arg TransitionVMParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionVM, arg.ID, arg.Column2, arg.State)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
