// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vms.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignIP = `-- name: AssignIP :exec
UPDATE ip_addresses SET vm_id = $2 WHERE id = $1
`

type AssignIPParams struct {
	ID   int64       `json:"id"`
	VmID pgtype.Int8 `json:"vm_id"`
}

func (q *Queries) AssignIP(ctx context.Context, arg AssignIPParams) error {
	_, err := q.db.Exec(ctx, assignIP, arg.ID, arg.VmID)
	return err
}

const claimFreeIP = `-- name: ClaimFreeIP :one
SELECT id, host(address)::text AS address, host(gateway)::text AS gateway
FROM ip_addresses
WHERE vm_id IS NULL AND region = $1
ORDER BY id
FOR UPDATE SKIP LOCKED
LIMIT 1
`

type ClaimFreeIPRow struct {
	ID      int64  `json:"id"`
	Address string `json:"address"`
	Gateway string `json:"gateway"`
}

func (q *Queries) ClaimFreeIP(ctx context.Context, region string) (ClaimFreeIPRow, error) {
	row := q.db.QueryRow(ctx, claimFreeIP, region)
	var i ClaimFreeIPRow
	err := row.Scan(&i.ID, &i.Address, &i.Gateway)
	return i, err
}

const countActiveVMs = `-- name: CountActiveVMs :one
SELECT count(*) FROM vms WHERE user_id = $1 AND state NOT IN ('deleted', 'error')
`

func (q *Queries) CountActiveVMs(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveVMs, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVM = `-- name: CreateVM :one
INSERT INTO vms (user_id, region, plan_id, template_id, proxmox_vmid, hostname, authorized_keys)
VALUES ($1, $2, $3, $4, nextval('vmid_seq')::int, $5, $6)
RETURNING id
`

type CreateVMParams struct {
	UserID         int64  `json:"user_id"`
	Region         string `json:"region"`
	PlanID         int64  `json:"plan_id"`
	TemplateID     int64  `json:"template_id"`
	Hostname       string `json:"hostname"`
	AuthorizedKeys string `json:"authorized_keys"`
}

func (q *Queries) CreateVM(ctx context.Context, arg CreateVMParams) (int64, error) {
	row := q.db.QueryRow(ctx, createVM,
		arg.UserID,
		arg.Region,
		arg.PlanID,
		arg.TemplateID,
		arg.Hostname,
		arg.AuthorizedKeys,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActivePlanBySlug = `-- name: GetActivePlanBySlug :one
SELECT id, slug, vcpu, ram_mb, disk_gb, price_uusdt_hourly, price_uusdt_monthly_cap, active FROM plans WHERE slug = $1 AND active
`

func (q *Queries) GetActivePlanBySlug(ctx context.Context, slug string) (Plan, error) {
	row := q.db.QueryRow(ctx, getActivePlanBySlug, slug)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Vcpu,
		&i.RamMb,
		&i.DiskGb,
		&i.PriceUusdtHourly,
		&i.PriceUusdtMonthlyCap,
		&i.Active,
	)
	return i, err
}

const getActiveTemplateBySlug = `-- name: GetActiveTemplateBySlug :one
SELECT id, slug, name, proxmox_template_id, active, ci_user FROM templates WHERE slug = $1 AND active
`

func (q *Queries) GetActiveTemplateBySlug(ctx context.Context, slug string) (Template, error) {
	row := q.db.QueryRow(ctx, getActiveTemplateBySlug, slug)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ProxmoxTemplateID,
		&i.Active,
		&i.CiUser,
	)
	return i, err
}

const getSSHKeysByIDs = `-- name: GetSSHKeysByIDs :many
SELECT public_key FROM ssh_keys WHERE user_id = $1 AND id = ANY($2::bigint[]) ORDER BY id
`

type GetSSHKeysByIDsParams struct {
	UserID  int64   `json:"user_id"`
	Column2 []int64 `json:"column_2"`
}

func (q *Queries) GetSSHKeysByIDs(ctx context.Context, arg GetSSHKeysByIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getSSHKeysByIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var public_key string
		if err := rows.Scan(&public_key); err != nil {
			return nil, err
		}
		items = append(items, public_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVM = `-- name: GetUserVM :one
SELECT v.id, v.region, v.hostname, v.state, v.ipv6, v.created_at,
       p.slug AS plan_slug, p.price_uusdt_hourly,
       t.slug AS template_slug, t.ci_user,
       COALESCE(host(ip.address), '')::text AS ipv4
FROM vms v
JOIN plans p ON p.id = v.plan_id
JOIN templates t ON t.id = v.template_id
LEFT JOIN ip_addresses ip ON ip.id = v.ipv4_id
WHERE v.id = $1 AND v.user_id = $2 AND v.deleted_at IS NULL
`

type GetUserVMParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetUserVMRow struct {
	ID               int64       `json:"id"`
	Region           string      `json:"region"`
	Hostname         string      `json:"hostname"`
	State            string      `json:"state"`
	Ipv6             pgtype.Text `json:"ipv6"`
	CreatedAt        time.Time   `json:"created_at"`
	PlanSlug         string      `json:"plan_slug"`
	PriceUusdtHourly int64       `json:"price_uusdt_hourly"`
	TemplateSlug     string      `json:"template_slug"`
	CiUser           string      `json:"ci_user"`
	Ipv4             string      `json:"ipv4"`
}

func (q *Queries) GetUserVM(ctx context.Context, arg GetUserVMParams) (GetUserVMRow, error) {
	row := q.db.QueryRow(ctx, getUserVM, arg.ID, arg.UserID)
	var i GetUserVMRow
	err := row.Scan(
		&i.ID,
		&i.Region,
		&i.Hostname,
		&i.State,
		&i.Ipv6,
		&i.CreatedAt,
		&i.PlanSlug,
		&i.PriceUusdtHourly,
		&i.TemplateSlug,
		&i.CiUser,
		&i.Ipv4,
	)
	return i, err
}

const getVMForWork = `-- name: GetVMForWork :one
SELECT v.id, v.user_id, v.hostname, v.state, v.proxmox_vmid, v.authorized_keys, v.ipv6, v.ipv4_id,
       p.vcpu, p.ram_mb, p.disk_gb,
       t.proxmox_template_id, t.ci_user,
       COALESCE(host(ip.address), '')::text AS ipv4,
       COALESCE(host(ip.gateway), '')::text AS gateway
FROM vms v
JOIN plans p ON p.id = v.plan_id
JOIN templates t ON t.id = v.template_id
LEFT JOIN ip_addresses ip ON ip.id = v.ipv4_id
WHERE v.id = $1
`

type GetVMForWorkRow struct {
	ID                int64       `json:"id"`
	UserID            int64       `json:"user_id"`
	Hostname          string      `json:"hostname"`
	State             string      `json:"state"`
	ProxmoxVmid       pgtype.Int4 `json:"proxmox_vmid"`
	AuthorizedKeys    string      `json:"authorized_keys"`
	Ipv6              pgtype.Text `json:"ipv6"`
	Ipv4ID            pgtype.Int8 `json:"ipv4_id"`
	Vcpu              int32       `json:"vcpu"`
	RamMb             int32       `json:"ram_mb"`
	DiskGb            int32       `json:"disk_gb"`
	ProxmoxTemplateID int32       `json:"proxmox_template_id"`
	CiUser            string      `json:"ci_user"`
	Ipv4              string      `json:"ipv4"`
	Gateway           string      `json:"gateway"`
}

func (q *Queries) GetVMForWork(ctx context.Context, id int64) (GetVMForWorkRow, error) {
	row := q.db.QueryRow(ctx, getVMForWork, id)
	var i GetVMForWorkRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.State,
		&i.ProxmoxVmid,
		&i.AuthorizedKeys,
		&i.Ipv6,
		&i.Ipv4ID,
		&i.Vcpu,
		&i.RamMb,
		&i.DiskGb,
		&i.ProxmoxTemplateID,
		&i.CiUser,
		&i.Ipv4,
		&i.Gateway,
	)
	return i, err
}

const listUserVMs = `-- name: ListUserVMs :many
SELECT v.id, v.region, v.hostname, v.state, v.ipv6, v.created_at,
       p.slug AS plan_slug, p.price_uusdt_hourly,
       t.slug AS template_slug, t.ci_user,
       COALESCE(host(ip.address), '')::text AS ipv4
FROM vms v
JOIN plans p ON p.id = v.plan_id
JOIN templates t ON t.id = v.template_id
LEFT JOIN ip_addresses ip ON ip.id = v.ipv4_id
WHERE v.user_id = $1 AND v.deleted_at IS NULL
ORDER BY v.id DESC
`

type ListUserVMsRow struct {
	ID               int64       `json:"id"`
	Region           string      `json:"region"`
	Hostname         string      `json:"hostname"`
	State            string      `json:"state"`
	Ipv6             pgtype.Text `json:"ipv6"`
	CreatedAt        time.Time   `json:"created_at"`
	PlanSlug         string      `json:"plan_slug"`
	PriceUusdtHourly int64       `json:"price_uusdt_hourly"`
	TemplateSlug     string      `json:"template_slug"`
	CiUser           string      `json:"ci_user"`
	Ipv4             string      `json:"ipv4"`
}

func (q *Queries) ListUserVMs(ctx context.Context, userID int64) ([]ListUserVMsRow, error) {
	rows, err := q.db.Query(ctx, listUserVMs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserVMsRow{}
	for rows.Next() {
		var i ListUserVMsRow
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.Hostname,
			&i.State,
			&i.Ipv6,
			&i.CreatedAt,
			&i.PlanSlug,
			&i.PriceUusdtHourly,
			&i.TemplateSlug,
			&i.CiUser,
			&i.Ipv4,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	err := row.Scan(&id)
	return id, err
}

const markVMDeleted = `-- name: MarkVMDeleted :exec
UPDATE vms SET state = 'deleted', deleted_at = now() WHERE id = $1
`

func (q *Queries) MarkVMDeleted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markVMDeleted, id)
	return err
}

const releaseIPForVM = `-- name: ReleaseIPForVM :exec
UPDATE ip_addresses SET vm_id = NULL WHERE vm_id = $1
`

func (q *Queries) ReleaseIPForVM(ctx context.Context, vmID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, releaseIPForVM, vmID)
	return err
}

const setVMIPv4 = `-- name: SetVMIPv4 :exec
UPDATE vms SET ipv4_id = $2 WHERE id = $1
`

type SetVMIPv4Params struct {
	ID     int64       `json:"id"`
	Ipv4ID pgtype.Int8 `json:"ipv4_id"`
}

func (q *Queries) SetVMIPv4(ctx context.Context, arg SetVMIPv4Params) error {
	_, err := q.db.Exec(ctx, setVMIPv4, arg.ID, arg.Ipv4ID)
	return err
}

const setVMIPv6 = `-- name: SetVMIPv6 :exec
UPDATE vms SET ipv6 = $2 WHERE id = $1
`

type SetVMIPv6Params struct {
	ID   int64       `json:"id"`
	Ipv6 pgtype.Text `json:"ipv6"`
}

func (q *Queries) SetVMIPv6(ctx context.Context, arg SetVMIPv6Params) error {
	_, err := q.db.Exec(ctx, setVMIPv6, arg.ID, arg.Ipv6)
	return err
}

const sumActiveHourly = `-- name: SumActiveHourly :one
SELECT COALESCE(sum(p.price_uusdt_hourly), 0)::bigint
FROM vms v JOIN plans p ON p.id = v.plan_id
WHERE v.user_id = $1 AND v.state NOT IN ('deleted', 'error')
`

func (q *Queries) SumActiveHourly(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumActiveHourly, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const transitionVM = `-- name: TransitionVM :execrows
UPDATE vms SET state = $3 WHERE id = $1 AND state = ANY($2::text[])
`

type TransitionVMParams struct {
	ID      int64    `json:"id"`
	Column2 []string `json:"column_2"`
	State   string   `json:"state"`
}

func (q *Queries) TransitionVM(ctx context.Context, arg TransitionVMParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionVM, arg.ID, arg.Column2, arg.State)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
